import urllib.request, urllib.parse
import re

stopwords = ['a', 'about', 'above', 'across', 'after', 'afterwards']
stopwords += ['again', 'against', 'all', 'almost', 'alone', 'along']
stopwords += ['already', 'also', 'although', 'always', 'am', 'among']
stopwords += ['amongst', 'amoungst', 'amount', 'an', 'and', 'another']
stopwords += ['any', 'anyhow', 'anyone', 'anything', 'anyway', 'anywhere']
stopwords += ['are', 'around', 'as', 'at', 'back', 'be', 'became']
stopwords += ['because', 'become', 'becomes', 'becoming', 'been']
stopwords += ['before', 'beforehand', 'behind', 'being', 'below']
stopwords += ['beside', 'besides', 'between', 'beyond', 'bill', 'both']
stopwords += ['bottom', 'but', 'by', 'call', 'can', 'cannot', 'cant']
stopwords += ['co', 'computer', 'con', 'could', 'couldnt', 'cry', 'de']
stopwords += ['describe', 'detail', 'did', 'do', 'done', 'down', 'due']
stopwords += ['during', 'each', 'eg', 'eight', 'either', 'eleven', 'else']
stopwords += ['elsewhere', 'empty', 'enough', 'etc', 'even', 'ever']
stopwords += ['every', 'everyone', 'everything', 'everywhere', 'except']
stopwords += ['few', 'fifteen', 'fifty', 'fill', 'find', 'fire', 'first']
stopwords += ['five', 'for', 'former', 'formerly', 'forty', 'found']
stopwords += ['four', 'from', 'front', 'full', 'further', 'get', 'give']
stopwords += ['go', 'had', 'has', 'hasnt', 'have', 'he', 'hence', 'her']
stopwords += ['here', 'hereafter', 'hereby', 'herein', 'hereupon', 'hers']
stopwords += ['herself', 'him', 'himself', 'his', 'how', 'however']
stopwords += ['hundred', 'i', 'ie', 'if', 'in', 'inc', 'indeed']
stopwords += ['interest', 'into', 'is', 'it', 'its', 'itself', 'keep']
stopwords += ['last', 'latter', 'latterly', 'least', 'less', 'ltd', 'made']
stopwords += ['many', 'may', 'me', 'meanwhile', 'might', 'mill', 'mine']
stopwords += ['more', 'moreover', 'most', 'mostly', 'move', 'much']
stopwords += ['must', 'my', 'myself', 'name', 'namely', 'neither', 'never']
stopwords += ['nevertheless', 'next', 'nine', 'no', 'nobody', 'none']
stopwords += ['noone', 'nor', 'not', 'nothing', 'now', 'nowhere', 'of']
stopwords += ['off', 'often', 'on', 'once', 'one', 'only', 'onto', 'or']
stopwords += ['other', 'others', 'otherwise', 'our', 'ours', 'ourselves']
stopwords += ['out', 'over', 'own', 'part', 'per', 'perhaps', 'please']
stopwords += ['put', 'rather', 're', 's', 'same', 'see', 'seem', 'seemed']
stopwords += ['seeming', 'seems', 'serious', 'several', 'she', 'should']
stopwords += ['show', 'side', 'since', 'sincere', 'six', 'sixty', 'so']
stopwords += ['some', 'somehow', 'someone', 'something', 'sometime']
stopwords += ['sometimes', 'somewhere', 'still', 'such', 'system', 'take']
stopwords += ['ten', 'than', 'that', 'the', 'their', 'them', 'themselves']
stopwords += ['then', 'thence', 'there', 'thereafter', 'thereby']
stopwords += ['therefore', 'therein', 'thereupon', 'these', 'they']
stopwords += ['thick', 'thin', 'third', 'this', 'those', 'though', 'three']
stopwords += ['three', 'through', 'throughout', 'thru', 'thus', 'to']
stopwords += ['together', 'too', 'top', 'toward', 'towards', 'twelve']
stopwords += ['twenty', 'two', 'un', 'under', 'until', 'up', 'upon']
stopwords += ['us', 'very', 'via', 'was', 'we', 'well', 'were', 'what']
stopwords += ['whatever', 'when', 'whence', 'whenever', 'where']
stopwords += ['whereafter', 'whereas', 'whereby', 'wherein', 'whereupon']
stopwords += ['wherever', 'whether', 'which', 'while', 'whither', 'who']
stopwords += ['whoever', 'whole', 'whom', 'whose', 'why', 'will', 'with']
stopwords += ['within', 'without', 'would', 'yet', 'you', 'your']
stopwords += ['yours', 'yourself', 'yourselves']

positivewords = ['able', 'abound', 'abounding', 'abounds', 'abracadabra', 'absolute', 'absolutely', 'absorbed',
                 'abundance', 'abundant', 'acaronar', 'accentuactivity', 'accept', 'acceptable', 'acceptance',
                 'accepted', 'accepting', 'accessible', 'acclaim', 'acclaimed', 'acclamation', 'accolade',
                 'accommodate', 'accommodated', 'accommodating', 'accommodation', 'accommodative', 'accomplish',
                 'accomplished', 'accomplishment', 'accomplishments', 'accountability', 'accuracy', 'accurate',
                 'accurately', 'achievable', 'achieve', 'achievement', 'achievements', 'acknowledgment', 'actability',
                 'action', 'activate', 'active', 'acts', 'acumen', 'adaptability', 'adaptable', 'adaptive', 'add',
                 'addition', 'adequate', 'adjectives', 'adjustable', 'admirable', 'admirably', 'admiration', 'admire',
                 'admired', 'admirer', 'admiring', 'admiringly', 'adorable', 'adore', 'adored', 'adorer', 'adoring',
                 'adoringly', 'adroit', 'adroitly', 'adulated', 'adulation', 'adulatory', 'advanced', 'advantage',
                 'advantageous', 'advantageously', 'advantages', 'adventure', 'adventuresome', 'adventurous',
                 'advocated', 'affability', 'affable', 'affably', 'affection', 'affectionate', 'affinity', 'affirm',
                 'affirmation', 'affirmations', 'affirmative', 'affluence', 'affluent', 'afford', 'affordable',
                 'affordably', 'ageless', 'agile', 'agilely', 'agility', 'agree', 'agreeable', 'agreeableness',
                 'agreeably', 'aid', 'aim', 'air', 'airness', 'akashic', 'alacrity', 'alert', 'alertness', 'aligned',
                 'alive', 'aliveness', 'allow', 'allowing', 'allure', 'alluring', 'alluringly', 'aloha', 'alternative',
                 'altitudinarian', 'altrucause', 'altruism', 'altruistic', 'altruistically', 'amaze', 'amazed',
                 'amazement', 'amazementpositive', 'amazes', 'amazing', 'amazingly', 'ambition', 'ambitious',
                 'ambitiously', 'ameliorate', 'amenity', 'amiability', 'amiable', 'amiably', 'amicability', 'amicable',
                 'amicably', 'amin', 'amity', 'ample', 'amply', 'amuse', 'amused', 'amusing', 'amusingly', 'angel',
                 'angelic', 'animate', 'animated', 'animateness', 'animating', 'animation', 'anticipation',
                 'apotheosis', 'appeal', 'appealing', 'applaud', 'appreciable', 'appreciate', 'appreciated',
                 'appreciates', 'appreciation', 'appreciative', 'appreciatively', 'appreciativeness', 'approach',
                 'appropriate', 'approval', 'approve', 'ardent', 'ardor', 'aroused', 'art', 'asq', 'assertive',
                 'assertiveness', 'assume', 'assurance', 'astonished', 'astonishing', 'astonishingly', 'astonishment',
                 'astounding', 'astronomical', 'attention', 'attentiveness', 'attitude', 'attraction', 'attractive',
                 'attributional', 'audacity', 'aurora', 'authentic', 'authenticity', 'awakening', 'aware', 'awareness',
                 'awe', 'awed', 'awesome', 'awesomeness', 'awesomenesspositive', 'badassery', 'badger', 'balance',
                 'balanced', 'ballistic', 'banner', 'based', 'beatify', 'beatitude', 'beautiful', 'beautifully',
                 'beautify', 'beauty', 'beingness', 'beliefs', 'believable', 'belong', 'belonging', 'beloved',
                 'benefactor', 'beneficial', 'benefit', 'benefits', 'benevolence', 'benevolent', 'benevolently', 'best',
                 'better', 'big', 'biophilia', 'blasting', 'blazing', 'bless', 'blessed', 'blessing', 'blessings',
                 'blinding', 'bling', 'bliss', 'blisscipline', 'blissful', 'blissfulness', 'blithesome', 'blood',
                 'bloom', 'blossom', 'blossoming', 'blowing', 'bohemian', 'boho', 'bold', 'boldness', 'bonus', 'box',
                 'bravery', 'breathtaking', 'breeziness', 'bright', 'brighten', 'brightness', 'brilliance', 'brilliant',
                 'brio', 'briskness', 'brothers', 'bubbling', 'buddhahood', 'budo', 'builder', 'bullishness',
                 'buoyancy', 'bustingeval', 'butterflies', 'calm', 'candor', 'capability', 'capable', 'capably',
                 'capital', 'care', 'carefree', 'carefreeness', 'carefulness', 'caress', 'caring', 'celebrate',
                 'celebration', 'centered', 'centering', 'cerebro', 'certain', 'certainty', 'chakra', 'challenge',
                 'champ', 'champion', 'change', 'changer', 'character', 'charisma', 'charismatic', 'charitable',
                 'charity', 'charm', 'charmer', 'charming', 'cheerful', 'cheerfulness', 'cheers', 'chi', 'chill',
                 'chode', 'choice', 'circumstances', 'citizen', 'clarity', 'classy', 'clean', 'cleanliness', 'clear',
                 'closed', 'closeness', 'cohesion', 'collaboration', 'collected', 'color', 'colors', 'comfort',
                 'comfortable', 'comforting', 'comment', 'comments', 'commentscomments', 'commitment', 'communication',
                 'communion', 'community', 'companionship', 'compassion', 'compassionate', 'competence', 'competency',
                 'competent', 'complimentary', 'composure', 'concentration', 'concord', 'confidence', 'confident',
                 'congruence', 'connect', 'connected', 'connectedness', 'connection', 'conquer', 'consciousness',
                 'considerate', 'consideration', 'consistency', 'consistent', 'constantly', 'constructive', 'content',
                 'contented', 'contentment', 'continual', 'continuity', 'continuous', 'contributing', 'contribution',
                 'conviction', 'convincing', 'cool', 'cooperation', 'copacabana', 'cordial', 'corking', 'cosmic',
                 'courage', 'courteous', 'courtesy', 'coziness', 'crank', 'create', 'creating', 'creative',
                 'creativeness', 'creativity', 'creator', 'cuddle', 'cuddling', 'curiosity', 'curious', 'currently',
                 'cute', 'cuteness', 'cutenesspositive', 'daily', 'daimon', 'dandy', 'daring', 'dauwtrappen', 'day',
                 'dazzle', 'dazzled', 'debonair', 'decent', 'decisiveness', 'dedicated', 'deeper', 'defencelessness',
                 'delicate', 'delicious', 'deliciousness', 'delight', 'delighted', 'delightful', 'delightfully',
                 'dependability', 'deserve', 'deservedness', 'deservingness', 'desirable', 'desire', 'detachment',
                 'determination', 'devoted', 'devotion', 'dictionary', 'difference', 'dignity', 'diligence',
                 'direction', 'dis', 'discipline', 'discovery', 'discretion', 'disney', 'distinguished', 'diversity',
                 'divine', 'dope', 'dragon', 'dream', 'dreamy', 'drive', 'duality', 'duty', 'dynamiceval', 'eager',
                 'eagerness', 'earnest', 'earthing', 'ease', 'easier', 'easily', 'easy', 'ebullience', 'ecosophy',
                 'ecstatic', 'ecstatify', 'educate', 'educated', 'education', 'effectiveness', 'efficacy', 'efficiency',
                 'efficient', 'effortless', 'effortlessly', 'effortlessness', 'ekaggata', 'elated', 'elation',
                 'electric', 'elegance', 'elena', 'elevate', 'elevated', 'embody', 'embrace', 'emotions', 'empathize',
                 'empathy', 'emphatic', 'empower', 'empowered', 'empowering', 'emulate', 'enable', 'enabled',
                 'enchanted', 'encourage', 'encouraged', 'encouragement', 'encouraging', 'endless', 'endurance',
                 'energetic', 'energize', 'energy', 'engage', 'engaged', 'engaging', 'engineering', 'engrossed',
                 'enjoy', 'enjoyment', 'enlightened', 'enlightenment', 'enlivened', 'enormous', 'enthralled',
                 'enthusiasm', 'enthusiastic', 'entranced', 'entries', 'equality', 'equanimity', 'equanimous',
                 'equitable', 'equitably', 'equity', 'erlebnis', 'esteem', 'eternal', 'ethereal', 'eudaemonism',
                 'eudaemonist', 'eudaemonistic', 'eudaimonia', 'eudamonia', 'eunoia', 'eval', 'events', 'evolve',
                 'exaltation', 'exalting', 'excellence', 'excellent', 'exceptional', 'excite', 'excited', 'excitement',
                 'exciting', 'exemplary', 'exhilarating', 'expansive', 'expectant', 'expected', 'experience',
                 'expertise', 'exploration', 'expressing', 'expression', 'expressiveness', 'exquisite', 'exstatisfy',
                 'extra', 'extraordinary', 'exuberance', 'exuberant', 'exultantpositive', 'ez_write_tag', 'ezslot_1',
                 'ezslot_11', 'ezslot_2', 'ezslot_3', 'ezslot_4', 'ezslot_5', 'ezslot_6', 'ezslot_7', 'ezslot_8',
                 'ezslot_9', 'fabulous', 'fair', 'fairness', 'faith', 'faithful', 'fame', 'family', 'famous', 'fancy',
                 'fantabulous', 'fantastic', 'fascinate', 'fascinated', 'favorite', 'fearless', 'feasible', 'feel',
                 'feeling', 'feelings', 'feels', 'feistiness', 'feisty', 'felicity', 'festive', 'festiveness',
                 'fidelity', 'fine', 'fit', 'flashy', 'flaunting', 'flawless', 'flawlessly', 'flexibility', 'flourish',
                 'flourishing', 'flow', 'flowing', 'focus', 'fog', 'fondle', 'food', 'forgive', 'forgiveness',
                 'forgiving', 'fortitude', 'fortuitous', 'fortune', 'free', 'freecycle', 'freedom', 'fric', 'friend',
                 'friendliness', 'friendly', 'friendship', 'frugality', 'ftw', 'fulfill', 'fulfilled', 'fun',
                 'funerific', 'funny', 'funology', 'futurepositive', 'game', 'gargantuan', 'gasmic', 'gemutlichkeit',
                 'generate', 'generator', 'generavity', 'generosity', 'generous', 'genial', 'genius', 'gentleman',
                 'genuine', 'genuineness', 'george', 'gibigiana', 'giddy', 'gift', 'giggling', 'gigil', 'ginger',
                 'giving', 'glad', 'glamor', 'glory', 'glow', 'god', 'goddess', 'godliness', 'going', 'goldilocks',
                 'good', 'goodness', 'goodwill', 'gorgeous', 'gorgeousness', 'grace', 'gracefully', 'graciousness',
                 'grand', 'grandiosity', 'gratefulness', 'gratification', 'gratitude', 'great', 'greatful', 'greatness',
                 'groovy', 'grounded', 'grow', 'growth', 'guidance', 'guide', 'guiding', 'gypsy', 'habituation',
                 'hakuna', 'halcyon', 'hall', 'halo', 'handsome', 'happily', 'happiness', 'happy', 'harmonious',
                 'harmonize', 'harmony', 'harness', 'headed', 'healing', 'health', 'healthy', 'heart', 'hearted',
                 'heartfelt', 'heartwarming', 'heaven', 'heavenly', 'heedful', 'heightened', 'hello', 'help', 'helpful',
                 'helpfulness', 'helping', 'hero', 'heroism', 'high', 'higher', 'highly', 'ho', 'holiness', 'holistic',
                 'holy', 'honest', 'honesty', 'honey', 'honor', 'hope', 'hopefulness', 'hospitable', 'hospitality',
                 'hot', 'huge', 'hum', 'human', 'humble', 'humored', 'humorpositive', 'ichariba', 'idea', 'idealism',
                 'identify', 'ikigai', 'illuminated', 'illumination', 'illustrious', 'imagination', 'improvement',
                 'inclusion', 'inclusiveness', 'incomparable', 'incredible', 'independence', 'indwelling',
                 'ineffability', 'ineffable', 'infinite', 'infinity', 'influence', 'ingenuity', 'inner', 'innocent',
                 'innovate', 'innovation', 'inquisitive', 'insight', 'insightful', 'insightfulness', 'inspiration',
                 'inspirational', 'inspire', 'inspired', 'inspiring', 'integrity', 'intelligence', 'intelligent',
                 'intensity', 'intention', 'interconnected', 'interconnectivity', 'interested', 'interesting',
                 'intimacy', 'intrepid', 'intrigued', 'intuition', 'intuitiveness', 'inventiveness', 'investing',
                 'invigorate', 'invigorated', 'invincible', 'involve', 'involved', 'iridescenteval', 'jammin', 'joke',
                 'jokes', 'jolly', 'jovial', 'joy', 'joyful', 'joyous', 'jubilant', 'jubilingo', 'jumpy', 'just',
                 'justice', 'juvenescentpositive', 'kaajhuab', 'kaleidoscopes', 'kalon', 'keen', 'ki', 'kibunpositive',
                 'kilig', 'kind', 'kindly', 'kindness', 'kiss', 'kittens', 'know', 'knowledge', 'known', 'koibito',
                 'large', 'laugh', 'laughing', 'leader', 'leaderboard', 'leadership', 'leading', 'learn', 'learning',
                 'leeway', 'let', 'letter', 'lettereval', 'letting', 'leveled', 'liberty', 'life', 'light',
                 'lightworker', 'like', 'list', 'live', 'liveliness', 'lively', 'lives', 'living', 'logic', 'longevity',
                 'lot', 'lovable', 'love', 'loved', 'lovely', 'lover', 'loving', 'loyal', 'loyalty', 'lucie', 'luck',
                 'lucky', 'lustrous', 'luxurypositive', 'ma', 'magic', 'magical', 'magnetic', 'magnificent', 'majesty',
                 'major', 'making', 'mani', 'marvelous', 'mastery', 'matata', 'matter', 'maturity', 'meaning',
                 'meaningful', 'meditation', 'medrectangle', 'meliorism', 'mellow', 'memorable', 'mench', 'mercy',
                 'merit', 'mild', 'mile', 'mind', 'minded', 'mindful', 'mindfulness', 'mindsight', 'miracle',
                 'mirthful', 'mobile', 'modesty', 'mojo', 'mood', 'morphing', 'motivate', 'motivated', 'motivating',
                 'motivation', 'motivational', 'mourning', 'moved', 'movement', 'moving', 'mutuality', 'myriadpositive',
                 'namaste', 'nature', 'navigationolder', 'neat', 'neoteny', 'new', 'nice', 'nirvana', 'noble', 'non',
                 'nourish', 'nourished', 'nourishing', 'nourishment', 'novaturient', 'nurture', 'nurturingeval',
                 'obedient', 'ok', 'okage', 'om', 'omg', 'omniscience', 'oneness', 'oneup', 'onwards', 'open',
                 'opening', 'openly', 'openness', 'opportunity', 'optimism', 'optimist', 'optimistic', 'order',
                 'orenda', 'organization', 'orientation', 'original', 'originality', 'outcome', 'outernationalist',
                 'outgoing', 'outstanding', 'overcome', 'overly', 'owning', 'pacify', 'padme', 'panache', 'paradise',
                 'paradisiac', 'pardon', 'participation', 'party', 'passion', 'passionate', 'patience', 'peace',
                 'peaceful', 'people', 'pep', 'peppiness', 'perceptiveness', 'perfect', 'perfection', 'perkiness',
                 'permalicious', 'perseverance', 'persistence', 'personal', 'petrichor', 'philocalist', 'phrases',
                 'pick', 'picturesque', 'pious', 'piquancy', 'play', 'playful', 'playfulness', 'pleased', 'pleasure',
                 'plucky', 'pm', 'pointedness', 'polite', 'politeness', 'pollyannaism', 'posichoice', 'posidriving',
                 'posifit', 'posilenz', 'posimass', 'posiminder', 'posiratio', 'posiripple', 'posirippler',
                 'posiripples', 'posisinger', 'posisite', 'posistrength', 'positibilitarian', 'positive',
                 'positivewordsresearch_com', 'positraction', 'positude', 'posivalues', 'posiword', 'possibilitarian',
                 'possibility', 'possible', 'pour', 'power', 'powerful', 'powerpositive', 'practicality', 'prana',
                 'precious', 'precision', 'preparedness', 'presence', 'present', 'preservation', 'pretty', 'priceless',
                 'pride', 'privacy', 'privilege', 'proactive', 'proactivity', 'process', 'progress', 'promptness',
                 'pronia', 'propitious', 'prosperity', 'prosperous', 'protect', 'proto', 'proud', 'punctual',
                 'punctuality', 'puppies', 'pure', 'purposepositive', 'quaint', 'quality', 'quantum', 'quantumness',
                 'queenly', 'questionnaire', 'quickening', 'quiddity', 'quiescent', 'quiet', 'quietnesspositive',
                 'radiant', 'radiate', 'rainbow', 'rapture', 'rapturous', 'rasasvada', 'rationality', 'ray',
                 'readiness', 'ready', 'real', 'reality', 'reason', 'reborn', 'recognition', 'recognize', 'recommend',
                 'records', 'refresh', 'refreshed', 'rejuvenate', 'rejuvenated', 'relatedness', 'relationships',
                 'relax', 'relaxed', 'releasing', 'relent', 'reliability', 'reliable', 'relief', 'relieve', 'relieved',
                 'religion', 'remarkable', 'renew', 'renewed', 'renowned', 'repose', 'research', 'resilience',
                 'resilient', 'resistance', 'resistant', 'resourcefulness', 'respect', 'respected', 'responsibility',
                 'rest', 'rested', 'restore', 'restored', 'revelation', 'reverence', 'revived', 'righteousness',
                 'rightful', 'ripe', 'risk', 'rockstar', 'romance', 'romantic', 'rosinesspositive', 'sacred', 'safe',
                 'safety', 'salvation', 'sama', 'sassy', 'satisfied', 'save', 'savings', 'savour', 'savouring', 'say',
                 'says', 'scope', 'secret', 'secure', 'secured', 'security', 'seen', 'self', 'selflessness', 'selling',
                 'serendipity', 'serene', 'serenity', 'serve', 'service', 'sexiness', 'sexual', 'sexy', 'shape',
                 'sharing', 'shelter', 'shift', 'shifting', 'shine', 'shining', 'simple', 'simplicity', 'simplify',
                 'sincerity', 'skill', 'skilled', 'slaying', 'sleep', 'smart', 'smile', 'smiling', 'soul', 'soulful',
                 'soulmate', 'soulpositive', 'space', 'spacious', 'spark', 'sparkle', 'sparkles', 'special',
                 'spectacular', 'spellbound', 'spirit', 'spirited', 'spiritedness', 'splendid', 'spontaneity',
                 'spontaneous', 'spunky', 'stability', 'start', 'starting', 'state', 'steadfastness', 'stellar',
                 'steps', 'stillness', 'stimulated', 'stimulating', 'stimulation', 'stream', 'strength', 'stretching',
                 'strive', 'strong', 'studious', 'study', 'stupendous', 'style', 'sublime', 'succulent', 'sufficient',
                 'sunniness', 'sunshine', 'supercalifragilistic', 'supercalifragilisticexpialidocious', 'supercharge',
                 'supercharged', 'superpower', 'support', 'supported', 'supporting', 'supreme', 'surprised', 'sustain',
                 'sustained', 'swag', 'swaggy', 'sweet', 'sweetheart', 'sweetness', 'sympathetic', 'symptoms',
                 'synchronicity', 'synergy', 'systematizationeval', 'tact', 'tags', 'taking', 'talk', 'tap', 'teach',
                 'teachable', 'team', 'teamwork', 'temul', 'tenacity', 'tender', 'tenderly', 'thank', 'thankful',
                 'thankfulness', 'therapy', 'thesaurus', 'things', 'thinking', 'thoughts', 'thrilled', 'thrive',
                 'thriving', 'tickled', 'tidsoptimist', 'time', 'timeliness', 'tionlessly', 'tolerance', 'touch',
                 'touched', 'tradition', 'traits', 'tranquil', 'tranquility', 'transform', 'transformation',
                 'transformative', 'transparent', 'triumph', 'true', 'trust', 'trusting', 'truth',
                 'truthfulnesspositive', 'ubuntu', 'ultimate', 'unabashed', 'unbearably', 'unbelievable',
                 'unconditional', 'underlined', 'understand', 'understanding', 'understood', 'unflappable', 'unhurry',
                 'unification', 'unique', 'unity', 'unreal', 'updated', 'updates', 'upgrade', 'uplift', 'upskill',
                 'use', 'useful', 'user', 'utter', 'valid', 'valuable', 'value', 'values', 'variety', 'veneration',
                 'verify', 'versatility', 'viable', 'vibrant', 'victorious', 'victory', 'vigor', 'vim', 'virtue',
                 'virtuoso', 'virtuous', 'vision', 'visioneval', 'vitality', 'vocabulary', 'vocabuleverage', 'vow',
                 'vulnerability', 'vulnerablepositive', 'walwalun', 'wanderlust', 'warm', 'warmth', 'water', 'wealth',
                 'web', 'welcome', 'welfare', 'wellbeing', 'wellness', 'wholeheartedly', 'wholeheartedness', 'willing',
                 'willingness', 'win', 'winnable', 'winning', 'wisdom', 'wise', 'won', 'wonder', 'wonderful',
                 'wondrous', 'word', 'words', 'working', 'world', 'worlds', 'worth', 'worthiness', 'worthy',
                 'wowpositive', 'xenial', 'xenodochial', 'xenophile', 'xfactor', 'xo', 'yaraana', 'yay', 'yea', 'yeah',
                 'year', 'yearn', 'yen', 'yes', 'yesability', 'yesable', 'yippee', 'young', 'youth', 'youthful',
                 'yugen', 'yummypositive', 'zajebiscie', 'zany', 'zappy', 'zeal', 'zealous', 'zest', 'zestful', 'zesty',
                 'zing', 'zippy']
negativewords = ['abnormal', 'abolish', 'abominable', 'abominably', 'abominate', 'abomination', 'abort', 'aborted',
                 'aborts', 'abrade', 'abrasive', 'abrupt', 'abruptly', 'abscond', 'absence', 'absent', 'absentee',
                 'absurd', 'absurdity', 'absurdly', 'absurdness', 'abuse', 'abused', 'abuses', 'abusive', 'abysmal',
                 'abysmally', 'abyss', 'accidental', 'accost', 'accursed', 'accusation', 'accusations', 'accuse',
                 'accuses', 'accusing', 'accusingly', 'acerbate', 'acerbic', 'acerbically', 'ache', 'ached', 'aches',
                 'aching', 'acrid', 'acridly', 'acridness', 'acrimonious', 'acrimoniously', 'acrimony', 'acted',
                 'adamant', 'adamantly', 'addict', 'addicted', 'addicting', 'addicts', 'admonish', 'admonisher',
                 'admonishingly', 'admonishment', 'admonition', 'adulterate', 'adulterated', 'adulteration',
                 'adversarial', 'adversary', 'adverse', 'adversity', 'advised', 'afflict', 'affliction', 'afflictive',
                 'affront', 'afraid', 'aggravate', 'aggravating', 'aggravation', 'aggression', 'aggressive',
                 'aggressiveness', 'aggressor', 'aggrieve', 'aggrieved', 'aghast', 'agonies', 'agonize', 'agonizing',
                 'agonizingly', 'agony', 'aground', 'ail', 'ailing', 'ailment', 'aimless', 'alarm', 'alarmed',
                 'alarming', 'alarmingly', 'alienate', 'alienated', 'alienation', 'allegation', 'allegations', 'allege',
                 'allergic', 'allergies', 'allergy', 'aloof', 'alphabetical', 'altercation', 'ambiguity', 'ambiguous',
                 'ambivalence', 'ambivalent', 'ambush', 'amiss', 'amputate', 'anarchism', 'anarchist', 'anarchistic',
                 'anarchy', 'anemic', 'anger', 'angrily', 'angriness', 'angry', 'anguish', 'animosity', 'annihilate',
                 'annihilation', 'annoy', 'annoyance', 'annoyances', 'annoyed', 'annoying', 'annoyingly', 'annoys',
                 'anomalous', 'anomaly', 'antagonism', 'antagonist', 'antagonistic', 'antagonize', 'anti', 'antipathy',
                 'antiquated', 'antithetical', 'anxieties', 'anxiety', 'anxious', 'anxiously', 'anxiousness',
                 'apathetic', 'apathetically', 'apathy', 'apocalypse', 'apocalyptic', 'apologist', 'apologists',
                 'appall', 'appalled', 'appalling', 'appallingly', 'apprehension', 'apprehensions', 'apprehensive',
                 'apprehensively', 'arbitrary', 'arcane', 'archaic', 'arduous', 'arduously', 'argumentative',
                 'arrogance', 'arrogant', 'arrogantly', 'ashamed', 'asinine', 'asininely', 'askance', 'asperse',
                 'aspersion', 'aspersions', 'assail', 'assassin', 'assassinate', 'assault', 'astray', 'asunder',
                 'atrocious', 'atrocities', 'atrocity', 'atrophy', 'attack', 'attacks', 'audacious', 'audaciously',
                 'audaciousness', 'audacity', 'austere', 'authoritarian', 'autocrat', 'autocratic', 'avalanche',
                 'avarice', 'avaricious', 'avariciously', 'avenge', 'averse', 'aversion', 'awe', 'awful', 'awfully',
                 'awfulness', 'awkward', 'awkwardness', 'axnegative', 'babble', 'backache', 'backaches', 'backbite',
                 'backbiting', 'backward', 'backwardness', 'backwoods', 'bad', 'badly', 'baffle', 'baffled',
                 'bafflement', 'baffling', 'bait', 'balanced', 'balk', 'banal', 'bane', 'banish', 'banishment',
                 'bankrupt', 'banner', 'barbarian', 'barbaric', 'barbarically', 'barbarity', 'barbarous', 'barbarously',
                 'barren', 'baseless', 'bash', 'bashed', 'bashful', 'bashing', 'battered', 'battering', 'batty',
                 'bearish', 'beastly', 'bedlam', 'bedlamite', 'befoul', 'beg', 'beggar', 'beggarly', 'begging',
                 'beguile', 'belabor', 'belated', 'beleaguer', 'belie', 'belittle', 'belittled', 'belittling',
                 'bellicose', 'belligerence', 'belligerent', 'belligerently', 'bemoan', 'bemoaning', 'bemused', 'bent',
                 'berate', 'bereave', 'bereavement', 'bereft', 'berserk', 'beseech', 'beset', 'besiege', 'besmirch',
                 'betray', 'betrayal', 'betrayals', 'betrayer', 'betraying', 'betrays', 'bewail', 'beware', 'bewilder',
                 'bewildered', 'bewildering', 'bewilderingly', 'bewilderment', 'bewitch', 'bias', 'biased', 'biases',
                 'bicker', 'bickering', 'bid', 'bigotries', 'bigotry', 'biting', 'bitingly', 'bitter', 'bitterly',
                 'bitterness', 'bizarre', 'blab', 'blabber', 'blackmail', 'blah', 'blame', 'blameworthy', 'bland',
                 'blandish', 'blaspheme', 'blasphemous', 'blasphemy', 'blasted', 'blatant', 'blatantly', 'blather',
                 'bleak', 'bleakly', 'bleakness', 'bleed', 'bleeding', 'bleeds', 'blemish', 'blessings', 'blind',
                 'blinding', 'blindingly', 'blindside', 'blister', 'blistering', 'bloated', 'blockage', 'blockhead',
                 'bloodshed', 'bloodthirsty', 'bloody', 'blotchy', 'blow', 'blown', 'blunder', 'blundering', 'blunders',
                 'blunt', 'blur', 'blurred', 'blurring', 'blurry', 'blurs', 'blurt', 'boastful', 'boggle', 'bogus',
                 'boil', 'boiling', 'boisterous', 'bomb', 'bombard', 'bombardment', 'bombastic', 'bondage', 'bonkers',
                 'bore', 'bored', 'boredom', 'bores', 'boring', 'botch', 'bother', 'bothered', 'bothering', 'bothers',
                 'bothersome', 'bowdlerize', 'box', 'boycott', 'braggart', 'bragger', 'brainless', 'brainwash', 'brash',
                 'brashly', 'brashness', 'brat', 'bravado', 'brazen', 'brazenly', 'brazenness', 'breach', 'break',
                 'breakdown', 'breaking', 'breaks', 'breakup', 'breakups', 'bribery', 'brimstone', 'bristle', 'brittle',
                 'broke', 'broken', 'brood', 'browbeat', 'bruise', 'bruised', 'bruises', 'bruising', 'brusque',
                 'brutal', 'brutalities', 'brutality', 'brutalize', 'brutalizing', 'brutally', 'brute', 'brutish',
                 'buckle', 'bug', 'bugging', 'buggy', 'bugs', 'bulkier', 'bulkiness', 'bulky', 'bull', 'bullies',
                 'bulls', 'bully', 'bullying', 'bullyingly', 'bum', 'bump', 'bumped', 'bumping', 'bumps', 'bumpy',
                 'bungle', 'bungler', 'bungling', 'bunk', 'burden', 'burdensome', 'burdensomely', 'burn', 'burned',
                 'burning', 'burns', 'bust', 'busts', 'busybody', 'butcher', 'butchery', 'buzzing', 'byzantinenegative',
                 'cackle', 'calamities', 'calamitous', 'calamitously', 'calamity', 'callous', 'calumniate',
                 'calumniation', 'calumnies', 'calumnious', 'calumniously', 'calumny', 'cancer', 'cancerous',
                 'cannibal', 'cannibalize', 'capitulate', 'capricious', 'capriciously', 'capriciousness', 'capsize',
                 'careless', 'carelessness', 'caricature', 'carnage', 'carp', 'cartoonish', 'cash', 'castigate',
                 'castrated', 'casualty', 'cat', 'cataclysm', 'cataclysmal', 'cataclysmic', 'cataclysmically',
                 'catastrophe', 'catastrophes', 'catastrophic', 'catastrophically', 'cats', 'caustic', 'caustically',
                 'cautionary', 'cave', 'censure', 'chafe', 'chaff', 'chagrin', 'challenging', 'chaos', 'chaotic',
                 'chasten', 'chastise', 'chastisement', 'chatter', 'chatterbox', 'cheap', 'cheapen', 'cheaply', 'cheat',
                 'cheated', 'cheater', 'cheating', 'cheats', 'checkered', 'cheerless', 'cheesy', 'chide', 'childish',
                 'chill', 'chilly', 'chintzy', 'choke', 'choleric', 'choppy', 'chore', 'chronic', 'chunky', 'ck',
                 'cking', 'clamor', 'clamorous', 'clash', 'class', 'clique', 'clog', 'clogged', 'clogs', 'cloud',
                 'clouding', 'cloudy', 'clueless', 'clumsy', 'clunky', 'coarse', 'coat', 'coated', 'cocky', 'coerce',
                 'coercion', 'coercive', 'cold', 'coldly', 'collapse', 'collude', 'collusion', 'combative', 'combust',
                 'comical', 'commiserate', 'commonplace', 'commotion', 'commotions', 'complacent', 'complain',
                 'complained', 'complaining', 'complains', 'complaint', 'complaints', 'complex', 'complicated',
                 'complication', 'complicit', 'compulsion', 'compulsive', 'concede', 'conceded', 'conceit', 'conceited',
                 'conceived', 'concern', 'concerned', 'concerns', 'concession', 'concessions', 'condemn', 'condemnable',
                 'condemnation', 'condemned', 'condemns', 'condescend', 'condescending', 'condescendingly',
                 'condescension', 'confess', 'confession', 'confessions', 'confidence', 'confined', 'conflict',
                 'conflicted', 'conflicting', 'conflicts', 'confound', 'confounded', 'confounding', 'confront',
                 'confrontation', 'confrontational', 'confuse', 'confused', 'confuses', 'confusing', 'confusion',
                 'confusions', 'congested', 'congestion', 'connect', 'cons', 'conservative', 'conspicuous',
                 'conspicuously', 'conspiracies', 'conspiracy', 'conspirator', 'conspiratorial', 'conspire',
                 'consternation', 'consuming', 'contagious', 'contaminate', 'contaminated', 'contaminates',
                 'contaminating', 'contamination', 'contempt', 'contemptible', 'contemptuous', 'contemptuously',
                 'contend', 'contention', 'contentious', 'contort', 'contortions', 'contradict', 'contradiction',
                 'contradictory', 'contrariness', 'contravene', 'contrive', 'contrived', 'controversial', 'controversy',
                 'convoluted', 'corrode', 'corrosion', 'corrosions', 'corrosive', 'corrupt', 'corrupted', 'corrupting',
                 'corruption', 'corrupts', 'costlier', 'costly', 'counter', 'counterproductive', 'coup', 'covetous',
                 'coward', 'cowardly', 'crabby', 'crack', 'cracked', 'cracks', 'craftily', 'crafty', 'cramp', 'cramped',
                 'cramping', 'cranky', 'crap', 'crappy', 'craps', 'crash', 'crashed', 'crashes', 'crashing', 'crass',
                 'craven', 'cravenly', 'craze', 'crazily', 'craziness', 'crazy', 'creak', 'creaking', 'creaks',
                 'credulous', 'creep', 'creeping', 'creeps', 'creepy', 'crept', 'crime', 'criminal', 'cringe',
                 'cringed', 'cringes', 'cripple', 'crippled', 'cripples', 'crippling', 'crisis', 'critic', 'critical',
                 'criticism', 'criticisms', 'criticize', 'criticized', 'criticizing', 'critics', 'cronyism', 'crook',
                 'crooked', 'crooks', 'crowded', 'crowdedness', 'crude', 'cruel', 'crueler', 'cruelest', 'cruelly',
                 'cruelness', 'cruelties', 'cruelty', 'crumble', 'crumbling', 'crummy', 'crumple', 'crumpled',
                 'crumples', 'crush', 'crushed', 'crushing', 'culpable', 'culprit', 'cumbersome', 'curse', 'cursed',
                 'curses', 'curt', 'cuss', 'cussed', 'cutthroat', 'cynical', 'cynicismeval', 'dally', 'damage',
                 'damaged', 'damages', 'damaging', 'damn', 'damnable', 'damnably', 'damnation', 'damned', 'damning',
                 'damper', 'danger', 'dangerous', 'dangerousness', 'dark', 'darken', 'darkened', 'darker', 'darkness',
                 'dastard', 'dastardly', 'daunt', 'daunting', 'dauntingly', 'dawdle', 'daze', 'dazed', 'dead',
                 'deadbeat', 'deadlock', 'deadly', 'deadweight', 'deaf', 'dearth', 'death', 'debacle', 'debase',
                 'debasement', 'debaser', 'debatable', 'debauch', 'debaucher', 'debauchery', 'debilitate',
                 'debilitating', 'debility', 'debt', 'debts', 'decadence', 'decadent', 'decay', 'decayed', 'deceit',
                 'deceitful', 'deceitfully', 'deceitfulness', 'deceive', 'deceiver', 'deceivers', 'deceiving',
                 'deception', 'deceptive', 'deceptively', 'declaim', 'decline', 'declines', 'declining', 'decrement',
                 'decrepit', 'decrepitude', 'decry', 'defamation', 'defamations', 'defamatory', 'defame', 'defeating',
                 'defect', 'defective', 'defects', 'defensive', 'defiance', 'defiant', 'defiantly', 'deficiencies',
                 'deficiency', 'deficient', 'defile', 'defiler', 'defined', 'deform', 'deformed', 'defrauding',
                 'defunct', 'defy', 'degenerate', 'degenerately', 'degeneration', 'degradation', 'degrade', 'degrading',
                 'degradingly', 'dehumanization', 'dehumanize', 'deign', 'deject', 'dejected', 'dejectedly',
                 'dejection', 'delay', 'delayed', 'delaying', 'delays', 'delinquency', 'delinquent', 'delirious',
                 'delirium', 'delude', 'deluded', 'deluge', 'delusion', 'delusional', 'delusions', 'demean',
                 'demeaning', 'demise', 'demolish', 'demolisher', 'demon', 'demonic', 'demonize', 'demonized',
                 'demonizes', 'demonizing', 'demoralize', 'demoralizing', 'demoralizingly', 'denial', 'denied',
                 'denies', 'denigrate', 'denounce', 'dense', 'dent', 'dented', 'dents', 'denunciate', 'denunciation',
                 'denunciations', 'deny', 'denying', 'deplete', 'deplorable', 'deplorably', 'deplore', 'deploring',
                 'deploringly', 'deprave', 'depraved', 'depravedly', 'deprecate', 'depress', 'depressed', 'depressing',
                 'depressingly', 'depression', 'depressions', 'deprive', 'deprived', 'deride', 'derision', 'derisive',
                 'derisively', 'derisiveness', 'derogatory', 'desecrate', 'desert', 'desertion', 'desiccate',
                 'desiccated', 'designed', 'desolate', 'desolately', 'desolation', 'despair', 'despairing',
                 'despairingly', 'desperate', 'desperately', 'desperation', 'despicable', 'despicably', 'despise',
                 'despised', 'despoil', 'despoiler', 'despondence', 'despondency', 'despondent', 'despondently',
                 'despot', 'despotic', 'despotism', 'destitute', 'destitution', 'destroy', 'destroyer', 'destruction',
                 'destructive', 'desultory', 'deter', 'deteriorate', 'deteriorating', 'deterioration', 'deterrent',
                 'detest', 'detestable', 'detestably', 'detested', 'detesting', 'detests', 'detract', 'detracted',
                 'detracting', 'detraction', 'detracts', 'detriment', 'detrimental', 'devastate', 'devastated',
                 'devastates', 'devastating', 'devastatingly', 'devastation', 'developed', 'deviate', 'deviation',
                 'devil', 'devilish', 'devilishly', 'devilment', 'devilry', 'devious', 'deviously', 'deviousness',
                 'devoid', 'diabolic', 'diabolical', 'diabolically', 'diametrically', 'diatribe', 'diatribes', 'dick',
                 'dictator', 'dictatorial', 'die', 'died', 'dies', 'difficult', 'difficulties', 'difficulty',
                 'diffidence', 'dilapidated', 'dilemma', 'dilly', 'dim', 'dimmer', 'ding', 'dings', 'dinky', 'dire',
                 'direly', 'direness', 'dirt', 'dirty', 'disable', 'disabled', 'disaccord', 'disadvantage',
                 'disadvantaged', 'disadvantageous', 'disadvantages', 'disaffect', 'disaffected', 'disaffirm',
                 'disagree', 'disagreeable', 'disagreeably', 'disagreed', 'disagreeing', 'disagreement', 'disagrees',
                 'disallow', 'disappoint', 'disappointed', 'disappointing', 'disappointingly', 'disappointment',
                 'disappointments', 'disappoints', 'disapprobation', 'disapproval', 'disapprove', 'disapproving',
                 'disarm', 'disarray', 'disaster', 'disastrous', 'disastrously', 'disavow', 'disavowal', 'disbelief',
                 'disbelieve', 'disbeliever', 'disclaim', 'discombobulate', 'discomfit', 'discomfort', 'discompose',
                 'disconcert', 'disconcerted', 'disconcerting', 'disconcertingly', 'disconsolate', 'disconsolately',
                 'disconsolation', 'discontent', 'discontented', 'discontentedly', 'discontinued', 'discontinuity',
                 'discontinuous', 'discord', 'discordance', 'discordant', 'discountenance', 'discourage',
                 'discouragement', 'discouraging', 'discouragingly', 'discourteous', 'discourteously', 'discredit',
                 'discrepant', 'discriminate', 'discrimination', 'discriminatory', 'disdain', 'disdained', 'disdainful',
                 'disdainfully', 'disfavor', 'disgrace', 'disgraced', 'disgraceful', 'disgracefully', 'disgruntle',
                 'disgruntled', 'disgust', 'disgusted', 'disgustedly', 'disgustful', 'disgustfully', 'disgusting',
                 'disgustingly', 'dishearten', 'disheartening', 'dishearteningly', 'dishonest', 'dishonestly',
                 'dishonesty', 'dishonor', 'dishonorable', 'disillusion', 'disillusioned', 'disillusionment',
                 'disillusions', 'disinclination', 'disinclined', 'disingenuous', 'disingenuously', 'disintegrate',
                 'disintegrated', 'disintegrates', 'disintegration', 'disinterest', 'disinterested', 'dislike',
                 'disliked', 'dislikes', 'disliking', 'dislocated', 'disloyal', 'disloyalty', 'dismal', 'dismally',
                 'dismalness', 'dismay', 'dismayed', 'dismaying', 'dismayingly', 'dismissive', 'dismissively',
                 'disobedience', 'disobedient', 'disobey', 'disorder', 'disordered', 'disorderly', 'disorganized',
                 'disorient', 'disoriented', 'disown', 'disparage', 'disparaging', 'disparagingly', 'dispensable',
                 'dispirit', 'dispirited', 'dispiritedly', 'dispiriting', 'displace', 'displaced', 'displease',
                 'displeased', 'displeasing', 'displeasure', 'disproportionate', 'disprove', 'disputable', 'dispute',
                 'disputed', 'disquiet', 'disquieting', 'disquietingly', 'disquietude', 'disregard', 'disregardful',
                 'disreputable', 'disrepute', 'disrespect', 'disrespectable', 'disrespectful', 'disrespectfully',
                 'disrespectfulness', 'disrespecting', 'disrupt', 'disruption', 'disruptive', 'dissatisfaction',
                 'dissatisfactory', 'dissatisfied', 'dissatisfies', 'dissatisfy', 'dissatisfying', 'dissed',
                 'dissemble', 'dissembler', 'dissension', 'dissent', 'dissenter', 'dissention', 'disservice', 'disses',
                 'dissidence', 'dissident', 'dissidents', 'dissing', 'dissocial', 'dissolute', 'dissolution',
                 'dissonance', 'dissonant', 'dissonantly', 'dissuade', 'dissuasive', 'distains', 'distaste',
                 'distasteful', 'distastefully', 'distort', 'distorted', 'distortion', 'distorts', 'distract',
                 'distracting', 'distraction', 'distraught', 'distraughtly', 'distress', 'distressed', 'distressing',
                 'distressingly', 'distrust', 'distrustful', 'distrusting', 'disturb', 'disturbance', 'disturbed',
                 'disturbing', 'disturbingly', 'disunity', 'disvalue', 'ditch', 'divergent', 'divisive', 'divisively',
                 'divisiveness', 'dizzy', 'doddering', 'dogged', 'doggedly', 'dogmatic', 'doldrums', 'domineer',
                 'domineering', 'doom', 'doomed', 'doomsday', 'dope', 'doubt', 'doubtful', 'doubtfully', 'doubts',
                 'douchebag', 'douchebags', 'downbeat', 'downcast', 'downer', 'downfall', 'downfallen', 'downgrade',
                 'downhearted', 'downheartedly', 'downhill', 'downside', 'downsides', 'downturn', 'downturns', 'drab',
                 'draconian', 'draconic', 'drag', 'dragged', 'dragging', 'dragoon', 'drags', 'drain', 'drained',
                 'draining', 'drains', 'drastic', 'drastically', 'drawback', 'drawbacks', 'dread', 'dreadful',
                 'dreadfully', 'dreadfulness', 'dreary', 'dripped', 'dripping', 'drippy', 'drips', 'drones', 'droop',
                 'droops', 'drop', 'dropout', 'dropouts', 'drought', 'drowning', 'drunk', 'drunkard', 'drunken',
                 'dubious', 'dubiously', 'dubitable', 'duck', 'dud', 'dull', 'dullard', 'dumb', 'dumbfound', 'dump',
                 'dumped', 'dumping', 'dumps', 'dunce', 'dungeon', 'dungeons', 'dupe', 'dust', 'dusty', 'dwindling',
                 'dyingnegative', 'earsplitting', 'eccentric', 'eccentricity', 'effigy', 'effrontery', 'egocentric',
                 'egomania', 'egotism', 'egotistical', 'egotistically', 'egregious', 'egregiously', 'election', 'elena',
                 'elimination', 'emaciated', 'emasculate', 'embarrass', 'embarrassing', 'embarrassingly',
                 'embarrassment', 'embattled', 'embroil', 'embroiled', 'embroilment', 'emergency', 'emotions',
                 'emphatic', 'emphatically', 'emptiness', 'encroach', 'encroachment', 'endanger', 'enemies', 'enemy',
                 'enervate', 'enfeeble', 'enflame', 'english', 'engulf', 'enjoin', 'enmity', 'enrage', 'enraged',
                 'enraging', 'enslave', 'entangle', 'entanglement', 'entrap', 'entrapment', 'envious', 'enviously',
                 'enviousness', 'epidemic', 'equivocal', 'erase', 'erode', 'erodes', 'erosion', 'err', 'errant',
                 'erratic', 'erratically', 'erroneous', 'erroneously', 'error', 'errors', 'eruptions', 'escapade',
                 'eschew', 'estranged', 'evade', 'eval', 'evasion', 'evasive', 'evil', 'evildoer', 'evils',
                 'eviscerate', 'exacerbate', 'exaggerate', 'exaggeration', 'exasperate', 'exasperated', 'exasperating',
                 'exasperatingly', 'exasperation', 'excessive', 'excessively', 'exclusion', 'excoriate', 'excruciating',
                 'excruciatingly', 'excuse', 'excuses', 'execrate', 'exhaust', 'exhausted', 'exhaustion', 'exhausts',
                 'exhort', 'exile', 'exorbitant', 'exorbitantly', 'expel', 'expensive', 'expire', 'expired', 'explode',
                 'exploit', 'exploitation', 'explosive', 'expropriate', 'expropriation', 'expulse', 'expunge',
                 'exterminate', 'extermination', 'extinguish', 'extort', 'extortion', 'extraneous', 'extravagance',
                 'extravagant', 'extravagantly', 'extremism', 'extremist', 'extremists', 'eyesorenegative',
                 'ez_write_tag', 'ezslot_1', 'ezslot_2', 'ezslot_3', 'ezslot_4', 'ezslot_5', 'ezslot_6', 'ezslot_7',
                 'ezslot_8', 'ezslot_9', 'fabricate', 'fabrication', 'faced', 'faces', 'facetious', 'facetiously',
                 'fail', 'failed', 'failing', 'fails', 'failure', 'failures', 'faint', 'fainthearted', 'faithless',
                 'fake', 'fall', 'fallacies', 'fallacious', 'fallaciously', 'fallaciousness', 'fallacy', 'fallen',
                 'falling', 'fallout', 'falls', 'false', 'falsehood', 'falsely', 'falsify', 'falter', 'faltered',
                 'famine', 'famished', 'fanatic', 'fanatical', 'fanatically', 'fanaticism', 'fanatics', 'fanciful',
                 'far', 'farce', 'farcical', 'farcically', 'farfetched', 'fascism', 'fascist', 'fastidious',
                 'fastidiously', 'fat', 'fatal', 'fatalistic', 'fatalistically', 'fatally', 'fated', 'fateful',
                 'fatefully', 'fathomless', 'fatigue', 'fatigued', 'fatty', 'fatuity', 'fatuous', 'fatuously', 'fault',
                 'faults', 'faulty', 'favored', 'fawningly', 'faze', 'fear', 'fearful', 'fearfully', 'fears',
                 'fearsome', 'feckless', 'fed', 'feeble', 'feebleminded', 'feed', 'feelings', 'feign', 'feint', 'fell',
                 'felon', 'felonious', 'ferociously', 'ferocity', 'fetched', 'fetid', 'fever', 'feverish', 'fevers',
                 'fiasco', 'fib', 'fibber', 'fickle', 'fiction', 'fictional', 'fictitious', 'fidget', 'fidgety',
                 'fiend', 'fiendish', 'fierce', 'figurehead', 'filth', 'filthy', 'finagle', 'finicky', 'fissures',
                 'fist', 'flabbergast', 'flabbergasted', 'flagging', 'flagrant', 'flagrantly', 'flair', 'flairs',
                 'flak', 'flake', 'flakey', 'flaking', 'flaky', 'flare', 'flares', 'flat', 'flaunt', 'flaw', 'flawed',
                 'flaws', 'flee', 'fleeing', 'fleer', 'flees', 'fleeting', 'flexing', 'flicker', 'flickering',
                 'flickers', 'flighty', 'flimflam', 'flimsy', 'flirt', 'flirty', 'floored', 'flounder', 'floundering',
                 'flout', 'fluster', 'foe', 'fool', 'fooled', 'foolhardy', 'foolish', 'foolishly', 'foolishness',
                 'forbid', 'forbidden', 'forbidding', 'forceful', 'foreboding', 'forebodingly', 'forfeit', 'forged',
                 'forgetful', 'forgetfully', 'forgetfulness', 'forlorn', 'forlornly', 'formed', 'forsake', 'forsaken',
                 'forswear', 'foul', 'foully', 'foulness', 'fractious', 'fractiously', 'fracture', 'fragile',
                 'fragmented', 'frail', 'frantic', 'frantically', 'franticly', 'fraud', 'fraudulent', 'fraught',
                 'frazzle', 'frazzled', 'freak', 'freaking', 'freakish', 'freakishly', 'freaks', 'freeze', 'freezes',
                 'freezing', 'frenetic', 'frenetically', 'frenzied', 'frenzy', 'fret', 'fretful', 'frets', 'friction',
                 'frictions', 'fried', 'frigging', 'fright', 'frighten', 'frightening', 'frighteningly', 'frightful',
                 'frightfully', 'frigid', 'frost', 'frown', 'froze', 'frozen', 'fruitless', 'fruitlessly', 'frustrate',
                 'frustrated', 'frustrates', 'frustrating', 'frustratingly', 'frustration', 'frustrations', 'fudge',
                 'fugitive', 'fulminate', 'fumble', 'fume', 'fumes', 'fundamentalism', 'funky', 'funnily', 'funny',
                 'furious', 'furiously', 'furor', 'fury', 'fuss', 'fussy', 'fustigate', 'fusty', 'futile', 'futilely',
                 'futility', 'fuzzynegative', 'gabble', 'gaff', 'gaffe', 'gainsay', 'gainsayer', 'gall', 'galling',
                 'gallingly', 'galls', 'gangster', 'gape', 'garbage', 'garish', 'gasp', 'gauche', 'gaudy', 'gawk',
                 'gawky', 'geezer', 'genic', 'genocide', 'ghastly', 'ghetto', 'ghosting', 'gibber', 'gibberish', 'gibe',
                 'giddy', 'gimmick', 'gimmicked', 'gimmicking', 'gimmicks', 'gimmicky', 'glare', 'glaringly', 'glib',
                 'glibly', 'glitch', 'glitches', 'gloatingly', 'gloom', 'gloomy', 'glower', 'glum', 'glut', 'gnawing',
                 'goad', 'goading', 'god', 'goof', 'goofy', 'goon', 'gossip', 'graceless', 'gracelessly', 'graft',
                 'grainy', 'grapple', 'grate', 'grating', 'gravely', 'greasy', 'greed', 'greedy', 'grief', 'grievance',
                 'grievances', 'grieve', 'grieving', 'grievous', 'grievously', 'grim', 'grimace', 'grind', 'gripe',
                 'gripes', 'grisly', 'gritty', 'gross', 'grossly', 'grotesque', 'grouch', 'grouchy', 'groundless',
                 'grouse', 'growl', 'grudge', 'grudges', 'grudging', 'grudgingly', 'gruesome', 'gruesomely', 'gruff',
                 'grumble', 'grumpier', 'grumpiest', 'grumpily', 'grumpy', 'guile', 'guilt', 'guiltily', 'guilty',
                 'gullible', 'gutless', 'gutternegative', 'hack', 'hacks', 'haggard', 'haggle', 'halfhearted',
                 'halfheartedly', 'hallucinate', 'hallucination', 'hamper', 'hampered', 'handed', 'handicapped', 'hang',
                 'hangs', 'haphazard', 'hapless', 'happy', 'harangue', 'harass', 'harassed', 'harasses', 'harassment',
                 'harboring', 'harbors', 'hard', 'hardball', 'harden', 'hardened', 'hardheaded', 'hardhearted',
                 'hardline', 'hardliner', 'hardliners', 'hardship', 'hardships', 'harm', 'harmed', 'harmful', 'harms',
                 'harpy', 'harridan', 'harried', 'harrow', 'harsh', 'harshly', 'hassle', 'hassled', 'hassles', 'haste',
                 'hastily', 'hasty', 'hate', 'hated', 'hateful', 'hatefully', 'hatefulness', 'hater', 'haters', 'hates',
                 'hating', 'hatred', 'haughtily', 'haughty', 'haunt', 'haunting', 'havoc', 'hawkish', 'haywire',
                 'hazard', 'hazardous', 'haze', 'hazy', 'head', 'headache', 'headaches', 'heartbreaker',
                 'heartbreaking', 'heartbreakingly', 'hearted', 'heartless', 'heathen', 'heavy', 'heavyhearted', 'heck',
                 'heckle', 'heckled', 'heckles', 'hectic', 'hedge', 'hedonistic', 'heedless', 'hefty', 'hegemony',
                 'heinous', 'hell', 'hellion', 'hells', 'helpless', 'helplessly', 'helplessness', 'heresy', 'heretic',
                 'heretical', 'hesitant', 'hideous', 'hideously', 'hideousness', 'high', 'hinder', 'hindrance', 'hiss',
                 'hissed', 'hissing', 'hit', 'ho', 'hoard', 'hoax', 'hobble', 'hogs', 'hollow', 'hoodwink', 'hooligan',
                 'hopeless', 'hopelessly', 'hopelessness', 'horde', 'horrendous', 'horrendously', 'horrible', 'horrid',
                 'horrific', 'horrified', 'horrifies', 'horrify', 'horrifying', 'hostage', 'hostile', 'hostilities',
                 'hostility', 'hotbeds', 'hothead', 'hotheaded', 'hothouse', 'hubris', 'huckster', 'hum', 'humid',
                 'humiliate', 'humiliating', 'humiliation', 'humming', 'hung', 'hurt', 'hurtful', 'hurting', 'hurts',
                 'hustler', 'hype', 'hyped', 'hypocrisy', 'hypocrite', 'hypocrites', 'hypocritical', 'hypocritically',
                 'hysteria', 'hysteric', 'hysterical', 'hysterically', 'hystericseval', 'idiocies', 'idiocy', 'idiot',
                 'idiotic', 'idiotically', 'idiots', 'idle', 'ignoble', 'ignominious', 'ignominiously', 'ignominy',
                 'ignorance', 'ignorant', 'ignore', 'ill', 'illegal', 'illegally', 'illegitimate', 'illicit',
                 'illiterate', 'illness', 'illogical', 'illogically', 'illusion', 'illusions', 'illusory', 'imaginary',
                 'imbalance', 'imbecile', 'imbroglio', 'immaterial', 'immature', 'imminence', 'imminently',
                 'immobilized', 'immoderate', 'immoderately', 'immodest', 'immoral', 'immorality', 'immorally',
                 'immovable', 'impair', 'impaired', 'impasse', 'impatience', 'impatient', 'impatiently', 'impeach',
                 'impedance', 'impede', 'impediment', 'impending', 'impenitent', 'imperfect', 'imperfection',
                 'imperfections', 'imperfectly', 'imperialist', 'imperil', 'imperious', 'imperiously', 'impermissible',
                 'impersonal', 'impertinent', 'impetuous', 'impetuously', 'impiety', 'impinge', 'impious', 'implacable',
                 'implausible', 'implausibly', 'implicate', 'implication', 'implode', 'impolite', 'impolitely',
                 'impolitic', 'importunate', 'importune', 'impose', 'imposers', 'imposing', 'imposition', 'impossible',
                 'impossibly', 'impotent', 'impoverish', 'impoverished', 'impractical', 'imprecate', 'imprecise',
                 'imprecisely', 'imprecision', 'imprison', 'imprisonment', 'improbability', 'improbable', 'improbably',
                 'improper', 'improperly', 'impropriety', 'imprudence', 'imprudent', 'impudence', 'impudent',
                 'impudently', 'impugn', 'impulsive', 'impulsively', 'impunity', 'impure', 'impurity', 'inability',
                 'inaccuracies', 'inaccuracy', 'inaccurate', 'inaccurately', 'inaction', 'inactive', 'inadequacy',
                 'inadequate', 'inadequately', 'inadvisable', 'inane', 'inanely', 'inappropriate', 'inappropriately',
                 'inapt', 'inarticulate', 'inattentive', 'inaudible', 'incapable', 'incapably', 'incautious',
                 'incendiary', 'incense', 'incessant', 'incessantly', 'incite', 'incitement', 'incivility', 'inclement',
                 'incoherence', 'incoherent', 'incoherently', 'incommensurate', 'incomparable', 'incomparably',
                 'incompatibility', 'incompatible', 'incompetence', 'incompetent', 'incompetently', 'incomplete',
                 'incomprehensible', 'incomprehension', 'inconceivable', 'inconceivably', 'incongruous',
                 'incongruously', 'inconsequential', 'inconsequentially', 'inconsiderate', 'inconsiderately',
                 'inconsistencies', 'inconsistency', 'inconsistent', 'inconsolable', 'inconsolably', 'inconstant',
                 'inconvenience', 'inconveniently', 'incorrect', 'incorrectly', 'incorrigible', 'incorrigibly',
                 'incredulous', 'incredulously', 'inculcate', 'indecency', 'indecent', 'indecently', 'indecision',
                 'indecisive', 'indecisively', 'indefensible', 'indelicate', 'indeterminable', 'indeterminably',
                 'indeterminate', 'indifference', 'indifferent', 'indigent', 'indignant', 'indignantly', 'indignation',
                 'indignity', 'indiscernible', 'indiscreet', 'indiscreetly', 'indiscretion', 'indiscriminate',
                 'indiscriminately', 'indistinguishable', 'indoctrinate', 'indoctrination', 'indolent', 'indulge',
                 'ineffective', 'ineffectively', 'ineffectiveness', 'ineffectual', 'ineffectually', 'inefficacy',
                 'inefficiency', 'inefficient', 'inefficiently', 'inelegance', 'inelegant', 'ineligible', 'inept',
                 'ineptitude', 'ineptly', 'inequalities', 'inequality', 'inequitable', 'inequitably', 'inequities',
                 'inescapable', 'inescapably', 'inessential', 'inevitable', 'inevitably', 'inexcusable', 'inexcusably',
                 'inexorable', 'inexorably', 'inexperience', 'inexperienced', 'inexpert', 'inexpertly', 'inexpiable',
                 'inextricable', 'inextricably', 'infamous', 'infamously', 'infamy', 'infected', 'infection',
                 'infections', 'inferior', 'inferiority', 'infernal', 'infest', 'infested', 'infidel', 'infidels',
                 'infiltrator', 'infiltrators', 'infirm', 'inflame', 'inflammation', 'inflammatory', 'inflated',
                 'inflationary', 'inflexible', 'inflict', 'infraction', 'infringe', 'infringement', 'infringements',
                 'infuriate', 'infuriated', 'infuriating', 'infuriatingly', 'inglorious', 'ingrate', 'ingratitude',
                 'inhibit', 'inhibition', 'inhospitable', 'inhuman', 'inhumane', 'inhumanity', 'inimical', 'inimically',
                 'iniquitous', 'iniquity', 'injudicious', 'injure', 'injurious', 'injury', 'injustice', 'injustices',
                 'innuendo', 'inoperable', 'inopportune', 'inordinate', 'inordinately', 'insane', 'insanely',
                 'insanity', 'insatiable', 'insecure', 'insecurity', 'insensible', 'insensitive', 'insensitively',
                 'insensitivity', 'insidious', 'insidiously', 'insignificance', 'insignificant', 'insignificantly',
                 'insincere', 'insincerely', 'insincerity', 'insinuate', 'insinuating', 'insinuation', 'insolence',
                 'insolent', 'insolently', 'insolvent', 'insouciance', 'instability', 'instigate', 'instigator',
                 'instigators', 'insubordinate', 'insubstantial', 'insubstantially', 'insufferable', 'insufferably',
                 'insufficiency', 'insufficient', 'insufficiently', 'insular', 'insult', 'insulted', 'insulting',
                 'insultingly', 'insults', 'insupportable', 'insurmountable', 'insurmountably', 'insurrection',
                 'intense', 'interested', 'interfere', 'interference', 'interferes', 'intermittent', 'interrupt',
                 'interruption', 'interruptions', 'intimidate', 'intimidating', 'intimidatingly', 'intimidation',
                 'intolerable', 'intolerance', 'intoxicate', 'intractable', 'intransigence', 'intransigent', 'intrude',
                 'intrusion', 'intrusive', 'inundate', 'inundated', 'invader', 'invalid', 'invalidate', 'invalidity',
                 'invasive', 'invective', 'inveigle', 'invidious', 'invidiously', 'invidiousness', 'invisible',
                 'involuntarily', 'involuntary', 'irascible', 'irate', 'irately', 'ire', 'irk', 'irked', 'irking',
                 'irks', 'irksome', 'irksomely', 'irksomeness', 'ironic', 'ironical', 'ironically', 'ironies', 'irony',
                 'irrational', 'irrationality', 'irrationally', 'irrationals', 'irreconcilable', 'irrecoverable',
                 'irrecoverably', 'irredeemable', 'irredeemably', 'irregular', 'irregularity', 'irrelevance',
                 'irrelevant', 'irreparable', 'irrepressible', 'irresolute', 'irresponsible', 'irresponsibly',
                 'irretrievable', 'irreversible', 'irritable', 'irritably', 'irritant', 'irritate', 'irritated',
                 'irritating', 'irritation', 'irritations', 'isolate', 'isolated', 'isolation', 'issue', 'issues',
                 'itch', 'itching', 'itchynegative', 'jabber', 'jaded', 'jagged', 'jam', 'jarring', 'jaundiced',
                 'jealous', 'jealously', 'jealousness', 'jealousy', 'jeer', 'jeering', 'jeeringly', 'jeers',
                 'jeopardize', 'jeopardy', 'jerk', 'jerky', 'jitter', 'jitters', 'jittery', 'job', 'jobless', 'joke',
                 'joker', 'jolt', 'judder', 'juddering', 'judders', 'jumpy', 'junk', 'junky', 'junkyardnegative',
                 'kill', 'killed', 'killer', 'killing', 'killjoy', 'kills', 'knave', 'knife', 'knock', 'knotted',
                 'known', 'kook', 'kookynegative', 'lack', 'lackadaisical', 'lacked', 'lackey', 'lackeys', 'lacking',
                 'lackluster', 'lacks', 'laconic', 'lag', 'lagged', 'lagging', 'lags', 'laid', 'lambast', 'lambaste',
                 'lame', 'lament', 'lamentable', 'lamentably', 'languid', 'languish', 'languor', 'languorous',
                 'languorously', 'lanky', 'lapse', 'lapsed', 'lapses', 'large', 'lascivious', 'latency', 'laughable',
                 'laughably', 'laughingstock', 'lawbreaker', 'lawbreaking', 'lawless', 'lawlessness', 'layoff', 'lazy',
                 'leader', 'leaderboard', 'leak', 'leakage', 'leakages', 'leaking', 'leaks', 'leaky', 'leaning',
                 'lecher', 'lecherous', 'lechery', 'leech', 'leer', 'leery', 'left', 'lemon', 'lengthy', 'lesser',
                 'letch', 'lethal', 'lethargic', 'lethargy', 'letter', 'letters', 'lewd', 'lewdly', 'lewdness',
                 'liability', 'liable', 'liar', 'liars', 'licentious', 'licentiously', 'licentiousness', 'lie', 'lied',
                 'lies', 'life', 'lifeless', 'light', 'like', 'limit', 'limitation', 'limitations', 'limited', 'limits',
                 'limp', 'liner', 'list', 'listless', 'litigious', 'little', 'lived', 'livid', 'lividly', 'loath',
                 'loathe', 'loathing', 'loathly', 'loathsome', 'loathsomely', 'logged', 'lone', 'loneliness', 'lonely',
                 'loner', 'lonesome', 'long', 'longing', 'longingly', 'loophole', 'loopholes', 'loose', 'loot', 'lose',
                 'loser', 'losers', 'loses', 'losing', 'loss', 'losses', 'lost', 'loud', 'louder', 'lousy', 'love',
                 'loveless', 'lovelorn', 'low', 'lowly', 'ludicrous', 'ludicrously', 'lugubrious', 'lukewarm', 'lull',
                 'lumpy', 'lunatic', 'lurch', 'lure', 'lurid', 'lurk', 'lurking', 'lyingnegative', 'macabre', 'mad',
                 'madden', 'maddening', 'maddeningly', 'madder', 'madly', 'madman', 'madness', 'maladjusted',
                 'maladjustment', 'malady', 'malaise', 'malcontent', 'malcontented', 'maledict', 'malevolence',
                 'malevolent', 'malevolently', 'malice', 'malicious', 'maliciously', 'maliciousness', 'malign',
                 'malignant', 'malodorous', 'maltreatment', 'mangle', 'mangled', 'mangles', 'mangling', 'mania',
                 'maniac', 'maniacal', 'manic', 'manipulate', 'manipulation', 'manipulative', 'manipulators',
                 'mannered', 'mar', 'marginal', 'marginally', 'martyrdom', 'mashed', 'massacre', 'massacres', 'matte',
                 'mawkish', 'mawkishly', 'mawkishness', 'meager', 'meaningless', 'meanness', 'measly', 'meddle',
                 'meddlesome', 'mediocre', 'mediocrity', 'medrectangle', 'melancholy', 'melodramatic',
                 'melodramatically', 'meltdown', 'menace', 'menacing', 'menacingly', 'mendacious', 'mendacity',
                 'menial', 'merciless', 'mercilessly', 'mess', 'messed', 'messes', 'messing', 'messy', 'midget', 'miff',
                 'militancy', 'minded', 'mindless', 'mindlessly', 'mirage', 'mire', 'misalign', 'misaligned',
                 'misaligns', 'misapprehend', 'misbecome', 'misbecoming', 'misbegotten', 'misbehave', 'misbehavior',
                 'miscalculate', 'miscalculation', 'miscellaneous', 'mischief', 'mischievous', 'mischievously',
                 'misconception', 'misconceptions', 'miscreant', 'miscreants', 'misdirection', 'miser', 'miserable',
                 'miserableness', 'miserably', 'miseries', 'miserly', 'misery', 'misfit', 'misfortune', 'misgiving',
                 'misgivings', 'misguidance', 'misguide', 'misguided', 'mishandle', 'mishap', 'misinform',
                 'misinformed', 'misinterpret', 'misjudge', 'misjudgment', 'mislead', 'misleading', 'misleadingly',
                 'mismanage', 'mispronounce', 'mispronounced', 'mispronounces', 'misread', 'misreading', 'misrepresent',
                 'misrepresentation', 'miss', 'missed', 'misses', 'misstatement', 'mist', 'mistake', 'mistaken',
                 'mistakenly', 'mistakes', 'mistress', 'mistrust', 'mistrustful', 'mistrustfully', 'mists',
                 'misunderstand', 'misunderstanding', 'misunderstandings', 'misunderstood', 'misuse', 'moan', 'mobster',
                 'mock', 'mocked', 'mockeries', 'mockery', 'mocking', 'mockingly', 'mocks', 'molest', 'molestation',
                 'monotonous', 'monotony', 'monster', 'monstrosities', 'monstrosity', 'monstrous', 'monstrously',
                 'moody', 'moot', 'mope', 'morbid', 'morbidly', 'mordant', 'mordantly', 'moribund', 'moron', 'moronic',
                 'morons', 'mortification', 'mortified', 'mortify', 'mortifying', 'motionless', 'motley', 'mourn',
                 'mourner', 'mournful', 'mournfully', 'moving', 'muddle', 'muddy', 'mudslinger', 'mudslinging',
                 'mulish', 'multi', 'mundane', 'murder', 'murderer', 'murderous', 'murderously', 'murky', 'muscle',
                 'mushy', 'musty', 'mysterious', 'mysteriously', 'mystery', 'mystify', 'mytheval', 'nag', 'nagging',
                 'naive', 'naively', 'narrower', 'nastily', 'nastiness', 'nasty', 'natured', 'naughty', 'nauseate',
                 'nauseates', 'nauseating', 'nauseatingly', 'naïve', 'nebulous', 'nebulously', 'needless', 'needlessly',
                 'needy', 'nefarious', 'nefariously', 'negate', 'negation', 'negative', 'negatives', 'negativity',
                 'neglect', 'neglected', 'negligence', 'negligent', 'nemesis', 'nepotism', 'nervous', 'nervously',
                 'nervousness', 'nettle', 'nettlesome', 'neurotic', 'neurotically', 'niggle', 'niggles', 'nightmare',
                 'nightmarish', 'nightmarishly', 'nitpick', 'nitpicking', 'noise', 'noises', 'noisier', 'noisy', 'non',
                 'nonexistent', 'nonresponsive', 'nonsense', 'nosey', 'notoriety', 'notorious', 'notoriously',
                 'noxious', 'nuisance', 'numbnegative', 'obese', 'object', 'objection', 'objectionable', 'objections',
                 'oblique', 'obliterate', 'obliterated', 'oblivious', 'obnoxious', 'obnoxiously', 'obscene',
                 'obscenely', 'obscenity', 'obscure', 'obscured', 'obscures', 'obscurity', 'obsess', 'obsessive',
                 'obsessively', 'obsessiveness', 'obsolete', 'obstacle', 'obstinate', 'obstinately', 'obstruct',
                 'obstructed', 'obstructing', 'obstruction', 'obstructs', 'obtrusive', 'obtuse', 'occlude', 'occluded',
                 'occludes', 'occluding', 'occupation', 'odd', 'odder', 'oddest', 'oddities', 'oddity', 'oddly', 'odor',
                 'offence', 'offend', 'offender', 'offending', 'offenses', 'offensive', 'offensively', 'offensiveness',
                 'officious', 'ominous', 'ominously', 'omission', 'omit', 'onerous', 'onerously', 'onslaught',
                 'opinionated', 'opponent', 'opportunistic', 'oppose', 'opposition', 'oppositions', 'oppress',
                 'oppression', 'oppressive', 'oppressively', 'oppressiveness', 'oppressors', 'ordeal', 'order',
                 'orphan', 'ostracize', 'outbreak', 'outburst', 'outbursts', 'outcast', 'outcry', 'outlaw', 'outmoded',
                 'outrage', 'outraged', 'outrageous', 'outrageously', 'outrageousness', 'outrages', 'outs', 'outsider',
                 'overact', 'overacted', 'overawe', 'overbalance', 'overbalanced', 'overbearing', 'overbearingly',
                 'overblown', 'overdo', 'overdone', 'overdue', 'overemphasize', 'overheat', 'overkill', 'overloaded',
                 'overlook', 'overpaid', 'overplay', 'overpower', 'overpriced', 'overrated', 'overreach', 'overrun',
                 'overshadow', 'oversight', 'oversights', 'oversimplification', 'oversimplified', 'oversimplify',
                 'oversize', 'overstate', 'overstated', 'overstatement', 'overstatements', 'overstates', 'overtaxed',
                 'overthrow', 'overthrows', 'overturn', 'overweight', 'overwhelm', 'overwhelmed', 'overwhelming',
                 'overwhelmingly', 'overwhelms', 'overzealous', 'overzealouslynegative', 'pain', 'painful', 'painfully',
                 'pains', 'pale', 'pales', 'paltry', 'pan', 'pandemonium', 'pander', 'pandering', 'panders', 'panic',
                 'panicked', 'panicking', 'panicky', 'par', 'paradoxical', 'paradoxically', 'paralyzed', 'paranoia',
                 'paranoid', 'parasite', 'pariah', 'parody', 'partiality', 'partisan', 'partisans', 'passive',
                 'passiveness', 'pathetic', 'pathetically', 'patronize', 'paucity', 'pauper', 'paupers', 'payback',
                 'peculiar', 'peculiarly', 'pedantic', 'peeled', 'peeve', 'peeved', 'peevish', 'peevishly', 'penalize',
                 'penalty', 'perfidious', 'perfunctory', 'peril', 'perilous', 'perilously', 'perish', 'pernicious',
                 'perplex', 'perplexed', 'perplexing', 'perplexity', 'persecute', 'persecution', 'pertinacious',
                 'pertinaciously', 'pertinacity', 'perturb', 'perturbed', 'pervasive', 'perverse', 'perversely',
                 'perversion', 'perversity', 'pervert', 'perverted', 'perverts', 'pessimism', 'pessimistic',
                 'pessimistically', 'pest', 'pestilent', 'petrified', 'petrify', 'pettifog', 'petty', 'phobia',
                 'phobic', 'phony', 'picket', 'picketed', 'picketing', 'pickets', 'picky', 'pig', 'pigs', 'pillage',
                 'pillory', 'pimple', 'pinch', 'pique', 'pitiable', 'pitiful', 'pitifully', 'pitiless', 'pitilessly',
                 'pittance', 'pity', 'plagiarize', 'plague', 'plaything', 'plea', 'pleas', 'plebeian', 'plight', 'plot',
                 'plotters', 'ploy', 'plunder', 'plunderer', 'pointless', 'pointlessly', 'poison', 'poisonous',
                 'poisonously', 'pokey', 'poky', 'polarization', 'pollute', 'polluter', 'polluters', 'pompous', 'poor',
                 'poorer', 'poorest', 'poorly', 'positive', 'positivewordsresearch_com', 'posturing', 'pout', 'poverty',
                 'powerless', 'prate', 'pratfall', 'prattle', 'precarious', 'precariously', 'precipitate',
                 'precipitous', 'predatory', 'predicament', 'prejudge', 'prejudice', 'prejudices', 'prejudicial',
                 'premeditated', 'preoccupy', 'preposterous', 'preposterously', 'presumptuous', 'presumptuously',
                 'pretend', 'pretense', 'pretentious', 'pretentiously', 'prevaricate', 'priced', 'pricey', 'pricier',
                 'prick', 'prickle', 'prickles', 'prideful', 'primitive', 'prison', 'prisoner', 'problem',
                 'problematic', 'problems', 'procrastinate', 'procrastinates', 'procrastination', 'productive',
                 'profane', 'profanity', 'prohibit', 'prohibitive', 'prohibitively', 'proliferation', 'propaganda',
                 'propagandize', 'proprietary', 'prosecute', 'protest', 'protested', 'protesting', 'protests',
                 'protracted', 'provocation', 'provocative', 'provoke', 'pry', 'pugnacious', 'pugnaciously',
                 'pugnacity', 'punch', 'punish', 'punishable', 'punitive', 'punk', 'puny', 'puppet', 'puppets', 'pure',
                 'puzzled', 'puzzlement', 'puzzlingnegative', 'quack', 'qualm', 'qualms', 'quandary', 'quarrel',
                 'quarrels', 'quarrelsome', 'quash', 'queer', 'questionable', 'quibble', 'quibbles', 'quitternegative',
                 'rabid', 'racism', 'racist', 'racists', 'racy', 'radical', 'radicalization', 'radically', 'radicals',
                 'rage', 'ragged', 'raging', 'rail', 'raked', 'rampage', 'rampant', 'ramshackle', 'rancor', 'randomly',
                 'rankle', 'rant', 'ranted', 'ranting', 'rants', 'rape', 'raped', 'raping', 'rascal', 'rascals', 'rash',
                 'rated', 'rattle', 'rattled', 'rattles', 'ravage', 'raving', 'reactionary', 'rebellious', 'rebuff',
                 'rebuke', 'recalcitrant', 'recant', 'recession', 'recessionary', 'reckless', 'recklessly',
                 'recklessness', 'recoil', 'recommend', 'recourses', 'redundancy', 'redundant', 'refusal', 'refuse',
                 'refused', 'refuses', 'refusing', 'refutation', 'refute', 'refuted', 'refutes', 'refuting', 'regress',
                 'regression', 'regressive', 'regret', 'regretful', 'regretfully', 'regrets', 'regrettable',
                 'regrettably', 'regretted', 'reject', 'rejected', 'rejecting', 'rejection', 'rejects', 'relapse',
                 'relentless', 'relentlessly', 'relentlessness', 'reluctance', 'reluctant', 'reluctantly', 'remorse',
                 'remorseful', 'remorsefully', 'remorseless', 'remorselessly', 'remorselessness', 'renounce',
                 'renunciation', 'repel', 'repetitive', 'reprehensible', 'reprehensibly', 'reprehension',
                 'reprehensive', 'represent', 'repress', 'repression', 'repressive', 'reprimand', 'reproach',
                 'reproachful', 'reprove', 'reprovingly', 'repudiate', 'repudiation', 'repugnance', 'repugnant',
                 'repugnantly', 'repulse', 'repulsed', 'repulsing', 'repulsive', 'repulsively', 'repulsiveness',
                 'research', 'resent', 'resentful', 'resentment', 'resignation', 'resigned', 'resistance', 'restless',
                 'restlessness', 'restrict', 'restricted', 'restriction', 'restrictive', 'resurgent', 'retaliate',
                 'retaliatory', 'reticent', 'retract', 'retreat', 'retreated', 'revenge', 'revengeful', 'revengefully',
                 'revert', 'revile', 'reviled', 'revoke', 'revolt', 'revolting', 'revoltingly', 'revulsion',
                 'revulsive', 'rhapsodize', 'rhetoric', 'rhetorical', 'ricer', 'rich', 'ridicule', 'ridicules',
                 'ridiculous', 'ridiculously', 'rife', 'rift', 'rifts', 'rigger', 'rigging', 'rigid', 'rigidity',
                 'rigidness', 'rile', 'riled', 'rip', 'ripped', 'risk', 'risks', 'risky', 'rival', 'rivalry',
                 'roadblocks', 'rocky', 'rogue', 'rollercoaster', 'rot', 'rotten', 'rough', 'rubbish', 'rude', 'rue',
                 'ruffian', 'ruffle', 'ruin', 'ruined', 'ruining', 'ruinous', 'ruins', 'rumbling', 'rumor', 'rumors',
                 'rumple', 'run', 'runaway', 'rupture', 'rust', 'rusts', 'rusty', 'rut', 'ruthless', 'ruthlessly',
                 'ruthlessness', 'rutseval', 'sabotage', 'sack', 'sacrificed', 'sad', 'sadden', 'sadly', 'sadness',
                 'sag', 'sagged', 'sagging', 'saggy', 'sags', 'salacious', 'sanctimonious', 'sap', 'sarcasm',
                 'sarcastic', 'sarcastically', 'sardonic', 'sardonically', 'sass', 'satirical', 'satirize', 'savage',
                 'savaged', 'savagery', 'savages', 'scaly', 'scam', 'scams', 'scandal', 'scandalize', 'scandalized',
                 'scandalous', 'scandalously', 'scandals', 'scant', 'scapegoat', 'scar', 'scarce', 'scarcely',
                 'scarcity', 'scare', 'scared', 'scarier', 'scariest', 'scarily', 'scarred', 'scars', 'scary',
                 'scathing', 'scathingly', 'scoff', 'scold', 'scolded', 'scolding', 'scorching', 'scorn', 'scornful',
                 'scornfully', 'scoundrel', 'scourge', 'scowl', 'scramble', 'scrambled', 'scrambles', 'scrambling',
                 'scrap', 'scratch', 'scratched', 'scratches', 'scratchy', 'scream', 'screech', 'screw', 'screwed',
                 'screwy', 'scuff', 'scuffs', 'scum', 'scummy', 'searching', 'second', 'secretive', 'sedentary',
                 'seedy', 'seeking', 'seethe', 'seething', 'self', 'selfish', 'selfishly', 'selfishness', 'senile',
                 'sensationalize', 'senseless', 'senselessly', 'seriousness', 'sermonize', 'serving', 'servitude',
                 'set', 'setback', 'setbacks', 'sever', 'severe', 'severity', 'shabby', 'shadowy', 'shady', 'shake',
                 'shaky', 'shallow', 'sham', 'shambles', 'shame', 'shameful', 'shamefully', 'shamefulness', 'shameless',
                 'shamelessly', 'shamelessness', 'shark', 'sharply', 'shatter', 'shimmer', 'shimmy', 'shipwreck',
                 'shirk', 'shirker', 'shiver', 'shock', 'shocked', 'shocking', 'shockingly', 'shoddy', 'short',
                 'shortage', 'shortchange', 'shortcoming', 'shortcomings', 'shortness', 'shortsighted',
                 'shortsightedness', 'showdown', 'shrew', 'shriek', 'shrill', 'shrilly', 'shrivel', 'shroud',
                 'shrouded', 'shrug', 'shun', 'shunned', 'sick', 'sicken', 'sickening', 'sickeningly', 'sickly',
                 'sickness', 'sided', 'sidetrack', 'sidetracked', 'siege', 'silly', 'simplistic', 'simplistically',
                 'sin', 'sinful', 'sinfully', 'sinister', 'sinisterly', 'sink', 'sinking', 'skeletons', 'skeptic',
                 'skeptical', 'skeptically', 'skepticism', 'sketchy', 'skimpy', 'skinny', 'skittish', 'skittishly',
                 'skulk', 'slack', 'slander', 'slanderer', 'slanderous', 'slanderously', 'slanders', 'slap', 'slashing',
                 'slaughter', 'slaughtered', 'slave', 'slaves', 'sleazy', 'slime', 'slog', 'slogged', 'slogging',
                 'slogs', 'sloppily', 'sloppy', 'sloth', 'slothful', 'slow', 'slowed', 'slower', 'slowest', 'slowly',
                 'slug', 'sluggish', 'slump', 'slumping', 'slur', 'sly', 'smack', 'smallish', 'smash', 'smear', 'smell',
                 'smelled', 'smelling', 'smells', 'smelly', 'smelt', 'smoke', 'smokescreen', 'smolder', 'smoldering',
                 'smother', 'smudge', 'smudged', 'smudges', 'smudging', 'smug', 'smugly', 'snag', 'snagged', 'snagging',
                 'snags', 'snappish', 'snappishly', 'snare', 'snarky', 'snarl', 'sneak', 'sneakily', 'sneaky', 'sneer',
                 'sneering', 'sneeringly', 'snob', 'snobbish', 'snobby', 'snobs', 'snub', 'soapy', 'sob', 'sober',
                 'sobering', 'social', 'solemn', 'solicitude', 'somber', 'sore', 'sorely', 'soreness', 'sorrow',
                 'sorrowful', 'sorrowfully', 'sorry', 'sorted', 'sour', 'sourly', 'spade', 'spank', 'spew', 'spewed',
                 'spewing', 'spews', 'spilling', 'spinster', 'spiritless', 'spite', 'spiteful', 'spitefully',
                 'spitefulness', 'splatter', 'split', 'splitting', 'spoil', 'spoilage', 'spoilages', 'spoiled',
                 'spoils', 'spook', 'spookier', 'spookiest', 'spookily', 'spooky', 'spoon', 'sporadic', 'spotty',
                 'spurious', 'spurn', 'sputter', 'squabble', 'squabbling', 'squander', 'squash', 'squeak', 'squeaks',
                 'squeaky', 'squeal', 'squealing', 'squeals', 'squirm', 'stab', 'stagnant', 'stagnate', 'stagnation',
                 'staid', 'stain', 'stains', 'stale', 'stalemate', 'stall', 'stalls', 'stammer', 'stampede',
                 'standstill', 'stark', 'starkly', 'start', 'startle', 'startling', 'startlingly', 'starvation',
                 'starve', 'static', 'steal', 'stealing', 'steals', 'steep', 'steeply', 'stench', 'stereotype',
                 'stereotypical', 'stereotypically', 'stern', 'stew', 'sticky', 'stiff', 'stiffness', 'stifle',
                 'stifling', 'stiflingly', 'stigma', 'stigmatize', 'sting', 'stinging', 'stingingly', 'stingy', 'stink',
                 'stinks', 'stodgy', 'stole', 'stolen', 'stooge', 'stooges', 'stormy', 'straggle', 'straggler',
                 'strain', 'strained', 'straining', 'strange', 'strangely', 'stranger', 'strangest', 'strangle',
                 'strapped', 'streaky', 'strenuous', 'stress', 'stresses', 'stressful', 'stressfully', 'stricken',
                 'strict', 'strictly', 'strident', 'stridently', 'strife', 'strike', 'stringent', 'stringently',
                 'struck', 'struggle', 'struggled', 'struggles', 'struggling', 'strut', 'stubborn', 'stubbornly',
                 'stubbornness', 'stuck', 'stuffy', 'stumble', 'stumbled', 'stumbles', 'stump', 'stumped', 'stumps',
                 'stun', 'stunt', 'stunted', 'stupid', 'stupidest', 'stupidity', 'stupidly', 'stupor', 'stutter',
                 'stuttered', 'stuttering', 'stutters', 'sty', 'stymied', 'sub', 'subdued', 'subjected', 'subjection',
                 'subjugate', 'subjugation', 'submissive', 'subordinate', 'subpoena', 'subpoenas', 'subservience',
                 'subservient', 'substandard', 'subtract', 'subversion', 'subversive', 'subversively', 'subvert',
                 'succumb', 'suck', 'sucked', 'sucker', 'sucks', 'sucky', 'sue', 'sued', 'sues', 'suffer', 'suffered',
                 'sufferer', 'sufferers', 'suffering', 'suffers', 'suffocate', 'sugar', 'sugarcoated', 'suicidal',
                 'suicide', 'sulk', 'sullen', 'sully', 'sunder', 'sunk', 'sunken', 'superficial', 'superficiality',
                 'superficially', 'superfluous', 'superstition', 'superstitious', 'suppress', 'suppression',
                 'surrender', 'susceptible', 'suspect', 'suspicion', 'suspicions', 'suspicious', 'suspiciously',
                 'swagger', 'swamped', 'sweaty', 'swelled', 'swelling', 'swindle', 'swipe', 'swollen', 'symptom',
                 'symptoms', 'syndromenegative', 'taboo', 'tacky', 'taint', 'tainted', 'tamper', 'tangle', 'tangled',
                 'tangles', 'tank', 'tanked', 'tanks', 'tantrum', 'tardy', 'tarnish', 'tarnished', 'tarnishes',
                 'tarnishing', 'tattered', 'taunt', 'taunting', 'tauntingly', 'taunts', 'taut', 'tawdry', 'taxing',
                 'tease', 'teasingly', 'tedious', 'tediously', 'temerity', 'temper', 'tempered', 'tempest',
                 'temptation', 'tenderness', 'tense', 'tension', 'tentative', 'tentatively', 'tenuous', 'tenuously',
                 'tepid', 'terrible', 'terribleness', 'terribly', 'terror', 'terrorism', 'terrorize', 'testily',
                 'testy', 'tetchily', 'tetchy', 'thankless', 'thicker', 'thirst', 'thorny', 'thoughtless',
                 'thoughtlessly', 'thoughtlessness', 'thrash', 'threat', 'threaten', 'threatening', 'threats',
                 'threesome', 'throb', 'throbbed', 'throbbing', 'throbs', 'throttle', 'thug', 'thumb', 'thumbs',
                 'thwart', 'tier', 'time', 'timid', 'timidity', 'timidly', 'tin', 'tingled', 'tingling', 'tired',
                 'tiresome', 'tiring', 'tiringly', 'toil', 'toll', 'topple', 'torment', 'tormented', 'torrent',
                 'tortuous', 'torture', 'tortured', 'tortures', 'torturing', 'torturous', 'torturously', 'totalitarian',
                 'touchy', 'toughness', 'tout', 'touted', 'touts', 'toxic', 'traduce', 'tragedy', 'tragic',
                 'tragically', 'traitor', 'traitorous', 'traitorously', 'tramp', 'trample', 'transgress',
                 'transgression', 'trap', 'trapped', 'trash', 'trashed', 'trashy', 'trauma', 'traumatic',
                 'traumatically', 'traumatize', 'traumatized', 'travesties', 'travesty', 'treacherous', 'treacherously',
                 'treachery', 'treason', 'treasonous', 'treated', 'treatment', 'trick', 'tricked', 'trickery', 'tricky',
                 'trivial', 'trivialize', 'trouble', 'troubled', 'troublemaker', 'troubles', 'troublesome',
                 'troublesomely', 'troubling', 'troublingly', 'truant', 'tumble', 'tumbled', 'tumbles', 'tumultuous',
                 'turbulent', 'turmoil', 'twist', 'twisted', 'twists', 'tyrannical', 'tyrannically', 'tyranny',
                 'tyrantnegative', 'ugh', 'uglier', 'ugliest', 'ugliness', 'ugly', 'ulterior', 'ultimatum',
                 'ultimatums', 'ultra', 'unable', 'unacceptable', 'unacceptably', 'unaccustomed', 'unachievable',
                 'unaffordable', 'unappealing', 'unattractive', 'unauthentic', 'unavailable', 'unavoidably',
                 'unbearable', 'unbelievable', 'unbelievably', 'uncaring', 'uncertain', 'uncivil', 'uncivilized',
                 'unclean', 'unclear', 'uncollectible', 'uncomfortable', 'uncomfortably', 'uncompetitive',
                 'uncompromising', 'uncompromisingly', 'unconfirmed', 'unconstitutional', 'uncontrolled',
                 'unconvincing', 'unconvincingly', 'uncooperative', 'uncouth', 'uncreative', 'undecided', 'undefined',
                 'undependability', 'undependable', 'undercut', 'undercuts', 'undercutting', 'underdog',
                 'underestimate', 'underlings', 'undermine', 'undermined', 'undermines', 'undermining', 'underpaid',
                 'underpowered', 'undersized', 'undesirable', 'undetermined', 'undid', 'undignified', 'undissolved',
                 'undocumented', 'undone', 'undue', 'unease', 'uneasily', 'uneasiness', 'uneasy', 'uneconomical',
                 'unemployed', 'unequal', 'unethical', 'uneven', 'uneventful', 'unexpected', 'unexpectedly',
                 'unexplained', 'unfairly', 'unfaithful', 'unfaithfully', 'unfamiliar', 'unfavorable', 'unfeeling',
                 'unfinished', 'unfit', 'unforeseen', 'unforgiving', 'unfortunate', 'unfortunately', 'unfounded',
                 'unfriendly', 'unfulfilled', 'unfunded', 'ungovernable', 'ungrateful', 'unhappily', 'unhappiness',
                 'unhappy', 'unhealthy', 'unhelpful', 'unilateralism', 'unimaginable', 'unimaginably', 'unimportant',
                 'uninformed', 'uninsured', 'unintelligible', 'unipolar', 'unjust', 'unjustifiable', 'unjustifiably',
                 'unjustified', 'unjustly', 'unkind', 'unkindly', 'unknown', 'unlawful', 'unlawfully', 'unlawfulness',
                 'unleash', 'unlicensed', 'unlikely', 'unlucky', 'unmoved', 'unnatural', 'unnaturally', 'unnecessary',
                 'unneeded', 'unnerve', 'unnerved', 'unnerving', 'unnervingly', 'unnoticed', 'unobserved', 'unorthodox',
                 'unorthodoxy', 'unpleasant', 'unpopular', 'unpredictable', 'unprepared', 'unproductive',
                 'unprofitable', 'unproved', 'unproven', 'unqualified', 'unravel', 'unraveled', 'unreachable',
                 'unreadable', 'unrealistic', 'unreasonable', 'unreasonably', 'unrelenting', 'unrelentingly',
                 'unreliability', 'unreliable', 'unresolved', 'unresponsive', 'unrest', 'unruly', 'unsafe',
                 'unsatisfactory', 'unsavory', 'unscrupulous', 'unscrupulously', 'unsecure', 'unseemly', 'unsettle',
                 'unsettled', 'unsettling', 'unsettlingly', 'unskilled', 'unsophisticated', 'unsound', 'unspeakable',
                 'unspecified', 'unstable', 'unsteadily', 'unsteadiness', 'unsteady', 'unsuccessful', 'unsuccessfully',
                 'unsupported', 'unsupportive', 'unsure', 'unsuspecting', 'unsustainable', 'untenable', 'untested',
                 'unthinkable', 'unthinkably', 'untimely', 'untouched', 'untrue', 'untrustworthy', 'untruthful',
                 'unusable', 'unusably', 'unusual', 'unusually', 'unwanted', 'unwarranted', 'unwatchable', 'unwelcome',
                 'unwell', 'unwieldy', 'unwilling', 'unwillingly', 'unwillingness', 'unwise', 'unwisely', 'unworkable',
                 'unworthy', 'unyielding', 'upbraid', 'upheaval', 'uprising', 'uproar', 'uproarious', 'uproariously',
                 'uproot', 'ups', 'upset', 'upsets', 'upsetting', 'upsettingly', 'urgent', 'usage', 'used', 'useless',
                 'usurp', 'usurper', 'utterlynegative', 'vagrant', 'vague', 'vagueness', 'vain', 'vainly', 'valuation',
                 'vanity', 'vehement', 'vehemently', 'vengeance', 'vengeful', 'vengefully', 'vengefulness', 'venom',
                 'venomous', 'venomously', 'vent', 'vestiges', 'vex', 'vexation', 'vexing', 'vexingly', 'vibrate',
                 'vibrated', 'vibrates', 'vibrating', 'vibration', 'vice', 'vicious', 'viciously', 'viciousness',
                 'victimize', 'viewable', 'vile', 'vileness', 'vilify', 'villainous', 'villainously', 'villains',
                 'vindictive', 'vindictively', 'vindictiveness', 'violate', 'violation', 'violator', 'violators',
                 'violent', 'violently', 'viper', 'virulence', 'virulent', 'virulently', 'virus', 'vocabulary',
                 'vociferous', 'vociferously', 'volatile', 'volatility', 'vomit', 'vomited', 'vomiting', 'vomits',
                 'vulgar', 'vulnerablenegative', 'wail', 'wallow', 'wane', 'waning', 'wanton', 'war', 'warily',
                 'wariness', 'warlike', 'warned', 'warning', 'warp', 'warped', 'wary', 'washed', 'waste', 'wasted',
                 'wasteful', 'wastefulness', 'wasting', 'water', 'watered', 'wayward', 'weak', 'weaken', 'weakening',
                 'weaker', 'weakness', 'weaknesses', 'weariness', 'wearisome', 'weary', 'wedge', 'weed', 'weep',
                 'weird', 'weirdly', 'wheedle', 'whimper', 'whine', 'whining', 'whiny', 'whips', 'white', 'wicked',
                 'wickedly', 'wickedness', 'wild', 'wildly', 'wiles', 'wilt', 'wily', 'wimpy', 'wince', 'winded',
                 'wobble', 'wobbled', 'wobbles', 'woe', 'woebegone', 'woeful', 'woefully', 'womanizer', 'womanizing',
                 'wood', 'woods', 'words', 'worn', 'worried', 'worriedly', 'worrier', 'worries', 'worrisome', 'worry',
                 'worrying', 'worryingly', 'worse', 'worsen', 'worsening', 'worst', 'worthless', 'worthlessly',
                 'worthlessness', 'wound', 'wounds', 'wrangle', 'wrath', 'wreak', 'wreaked', 'wreaks', 'wreck', 'wrest',
                 'wrestle', 'wretch', 'wretched', 'wretchedly', 'wretchedness', 'wrinkle', 'wrinkled', 'wrinkles',
                 'writhe', 'wrong', 'wrongful', 'wrongly', 'wroughteval', 'yawnnegative', 'zap', 'zapped', 'zaps',
                 'zealot', 'zealous', 'zealously', 'zombie']


def countNegativewords(wordlistDict, negativewords):
    number = 0;
    for i in range(len(wordlistDict)):
        if wordlistDict[i][1] in negativewords:
            number += 1;
    return number;


def countPositivewords(wordlistDict, positivewords):
    number = 0;
    for i in range(len(wordlistDict)):
        if wordlistDict[i][1] in positivewords:
            number += 1;
    return number;


def removeStopwords(wordlist, stopwords): #O(nm)
    return [w for w in wordlist if w not in stopwords]


def removeDigit(wordlist):
    return [w for w in wordlist if w.isdigit() == False]


def removeSingleWord(wordlist):
    return [w for w in wordlist if len(w) > 1]


def stripNonAlphaNum(text):
    return re.compile(r'\W+', re.UNICODE).split(text) #0-9, a-z, A-Z, _


def wordListToFreqDict(wordlist):
    wordfreq = [wordlist.count(p) for p in wordlist]
    return dict(list(zip(wordlist, wordfreq)))


def sortFreqDict(freqdict):
    aux = [(freqdict[key], key) for key in freqdict]
    aux.sort()
    aux.reverse()
    return aux


def sortFreqDictMine(freqdict):
    aux = [key for key in freqdict]
    aux.sort()
    return aux


def stripTags(pageContents):
    startLoc = pageContents.find("<p>")
    endLoc = pageContents.rfind("</p>")

    pageContents = pageContents[startLoc:endLoc]

    inside = 0
    text = ''

    for char in pageContents:
        if char == '<':
            inside = 1
        elif (inside == 1 and char == '>'):
            inside = 0
        elif inside == 1:
            continue
        else:
            text += char
    return text

positiveWords = 'https://positivewordsresearch.com/list-of-positive-words/'
negativeWords = 'https://positivewordsresearch.com/list-of-negative-words/'
train = 'https://penanglocal.com/2019/01/21/kuala-lumpur-to-penang-by-train-travel-review/'
bus = 'https://www.bookaway.com/blog/a-luxury-bus-ride-from-penang-to-kuala-lumpur-a-guest-review'
flight = 'https://flight-report.com/en/report/29844/Air-Asia-AK6112-Kuala-Lumpur-KUL-Penang-PEN'
grab = 'https://www.thestar.com.my/opinion/letters/2018/10/29/why-grab-leads-the-way-in-transport-service'

urlList = [train, bus, flight, grab]

for url in urlList:
    print(url)
    response = urllib.request.urlopen(url)
    HTML = response.read()
    text = stripTags(HTML.decode("utf-8").lower())
    fullwordlist = stripNonAlphaNum(text)
    wordlist = removeStopwords(fullwordlist, stopwords)
    wordlist = removeDigit(wordlist)
    wordlist = removeSingleWord(wordlist)
    dictionary = wordListToFreqDict(wordlist)
    sorteddict = sortFreqDict(dictionary)
    # for s in sorteddict: print(str(s))
    number = 0
    for s in sorteddict:
        number += int(s[0])
    print(number)
    print(countNegativewords(sorteddict, negativewords))
    print(countPositivewords(sorteddict, positivewords))

# # f = open("", "a")
# f.write(str(sorteddict))
# f.close()
# print(sorteddict)
